const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const dataRoot = path.join(root, 'data');
const outputPath = path.join(dataRoot, 'berlin-runner-decks.js');

const deckDirs = [
  'goethe-a1', 'goethe-a2', 'goethe-b1',
  'netzwerk-a1', 'netzwerk-a2', 'netzwerk-b1',
  'vielfalt-b1plus', 'vielfalt-b2-1', 'vielfalt-b2-2',
  'aspekte-b2', 'vielfalt-c1-1', 'vielfalt-c1-2', 'aspekte-c1'
];

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function isSafeNoun(entry) {
  const safety = entry.learnerSafety || {};
  return /^(der|die|das)$/.test(entry.article) && entry.active !== false &&
    entry.learnerSafe !== false && safety.excludeFromCoreDrills !== true &&
    safety.excludeFromCoreLemmaDrills !== true;
}

const sourceNouns = readJson(path.join(dataRoot, 'nouns.json')).nouns.filter(isSafeNoun);
// The fourth column is the English gloss, and it is the reason this file is
// worth its size. The runner reads glosses from data/nouns.json, and `fetch`
// is blocked on file:// - so a double-clicked page showed a translation only
// for the 756 words hard-coded into the HTML, i.e. under 7% of a Top 10000
// deck. This bundle is delivered by a <script> tag, which file:// does allow,
// so carrying the glosses here is what makes every deck fully glossed offline.
// Costs ~514 KB on a file that is only fetched once the player opens the deck
// catalogue at all.
const compactNouns = sourceNouns.map(entry => [
  entry.word, entry.article, entry.rank || 0, String(entry.english || '').trim()
]);
const byId = new Map();
const byWord = new Map();

sourceNouns.forEach((entry, index) => {
  if (entry.id) byId.set(entry.id, index);
  const previousIndex = byWord.get(entry.word);
  const previous = previousIndex === undefined ? null : sourceNouns[previousIndex];
  const priority = entry.sensePriority === undefined ? 100 : entry.sensePriority;
  const previousPriority = previous && previous.sensePriority === undefined ? 100 :
    (previous ? previous.sensePriority : Infinity);
  if (!previous || priority < previousPriority ||
      (priority === previousPriority && (entry.rank || Infinity) < (previous.rank || Infinity))) {
    byWord.set(entry.word, index);
  }
});

const groups = [];
for (const dirName of deckDirs) {
  const dir = path.join(dataRoot, dirName);
  const manifest = readJson(path.join(dir, 'manifest.json'));
  const decks = [];
  for (const ref of manifest.decks || []) {
    if (!ref.file || ref.kind === 'verb_forms' || ref.kind === 'verb_prepositions') continue;
    const deckPath = path.join(dir, ref.file);
    if (!fs.existsSync(deckPath)) continue;
    const deck = readJson(deckPath);
    if (!Array.isArray(deck.nouns) || !deck.nouns.length) continue;
    const indices = [];
    const seen = new Set();
    for (const name of deck.nouns) {
      const index = byId.has(name) ? byId.get(name) : byWord.get(name);
      if (index === undefined || seen.has(index)) continue;
      seen.add(index);
      indices.push(index);
    }
    if (indices.length < 3) continue;
    decks.push({
      id: deck.id || ref.id || `${dirName}-${ref.file}`,
      name: deck.shortName || ref.name || deck.name || ref.file,
      fullName: deck.name || ref.name || ref.file,
      nouns: indices
    });
  }
  if (decks.length) groups.push({ name: manifest.name || dirName, decks });
}

const payload = {
  version: '2026-08-27',
  nouns: compactNouns,
  groups
};

const banner = '// Generated by scripts/build_berlin_runner_decks.js; do not edit by hand.\n';
fs.writeFileSync(outputPath, `${banner}window.ARTIKEL_EXPRESS_DECK_DATA=${JSON.stringify(payload)};\n`, 'utf8');
console.log(`Wrote ${path.relative(root, outputPath)} with ${compactNouns.length} nouns and ${groups.reduce((n, group) => n + group.decks.length, 0)} decks.`);
