const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const dataRoot = path.join(root, 'data');
const outputPath = path.join(dataRoot, 'berlin-runner-decks.js');

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function isSafeNoun(entry) {
  const safety = entry.learnerSafety || {};
  return /^(der|die|das)$/.test(entry.article) && entry.active !== false &&
    entry.learnerSafe !== false && safety.excludeFromCoreDrills !== true &&
    safety.excludeFromCoreLemmaDrills !== true;
}

const sourceNouns = readJson(path.join(dataRoot, 'nouns.json')).nouns.filter(isSafeNoun);
// The fourth column is the English gloss, and it is the reason this file is
// worth its size. The runner reads glosses from data/nouns.json, and `fetch`
// is blocked on file:// - so a double-clicked page showed a translation only
// for the 756 words hard-coded into the HTML, i.e. under 7% of a large
// deck. This bundle is delivered by a <script> tag, which file:// does allow,
// so carrying the glosses here is what makes every deck fully glossed offline.
// Costs ~514 KB on a file that is only fetched once the player opens the deck
// catalogue at all.
const compactNouns = sourceNouns.map(entry => [
  entry.word, entry.article, entry.rank || 0, String(entry.english || '').trim()
]);
const payload = {
  version: '2026-09-26',
  nouns: compactNouns,
  groups: []
};

const banner = '// Generated by scripts/build_berlin_runner_decks.js; do not edit by hand.\n';
fs.writeFileSync(outputPath, `${banner}window.ARTIKEL_EXPRESS_DECK_DATA=${JSON.stringify(payload)};\n`, 'utf8');
console.log(`Wrote ${path.relative(root, outputPath)} with ${compactNouns.length} nouns.`);
