#!/usr/bin/env python3
"""Batch 4: adjective blanks rank 3500-5000 (selection)."""
import json, sys
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8')
ROOT = Path(__file__).resolve().parent.parent

ADJ = {
    'reformatorisch':'Reformation / reformatory','reichweitenstark':'with wide reach / popular',
    'schrumpfend':'shrinking','selbstgebastelt':'self-made / DIY','selbstironisch':'self-ironic',
    'sinnstiftend':'meaningful / purpose-giving','stilsicher':'stylistically confident',
    'substantiell':'substantial','texanisch':'Texan','tonnenschwer':'weighing tonnes / very heavy',
    'außerbetrieblich':'extra-operational / outside the company','beamtet':'civil-service',
    'begrünt':'greened / planted','bewachsen':'overgrown','dreigeschossig':'three-storey',
    'eingeschossig':'single-storey','elektrifiziert':'electrified',
    'entwicklungspsychologisch':'developmental-psychology','freilaufend':'free-range',
    'hinderlich':'obstructive / hindering','naturgetreu':'true to nature / lifelike',
    'neugotisch':'Neo-Gothic','pornografisch':'pornographic','rosarot':'pink / rose-coloured',
    'stiefmütterlich':'stepmotherly / neglected','südländisch':'southern (European)',
    'umrandet':'bordered / edged','unanfechtbar':'unchallengeable / incontestable',
    'unbeachtet':'unnoticed / disregarded','unbeantwortet':'unanswered',
    'ungeübt':'unpractised / inexperienced','unterjährig':'sub-annual / within a year',
    'vaterländisch':'patriotic','viermonatig':'four-month','zehntägig':'ten-day',
    'zielgruppengerecht':'target-audience appropriate','zivilisatorisch':'civilizational',
    'abteilungsübergreifend':'cross-departmental','apostolisch':'apostolic',
    'arbeitsmarktpolitisch':'labour-market-policy','ausdifferenziert':'differentiated',
    'bereichsübergreifend':'cross-area / cross-divisional','berührungsempfindlich':'touch-sensitive',
    'bildungswissenschaftlich':'educational-science','bundespolitisch':'federal-political',
    'demonstrativ':'demonstrative','französischsprachig':'French-speaking',
    'friedvoll':'peaceful','gefräßig':'voracious / gluttonous','gehbehindert':'walking-impaired',
    'gradlinig':'straight / straightforward','krankenversichert':'covered by health insurance',
    'lebensfroh':'cheerful / full of life','messerscharf':'razor-sharp',
    'parkähnlich':'park-like','populärwissenschaftlich':'popular-science',
    'publik':'public','reaktionsschnell':'quick-reacting','rechtsrheinisch':'east of the Rhine',
    'rosafarben':'pink','strafbewehrt':'subject to penalty','symphonisch':'symphonic',
    'theatral':'theatrical','unattraktiv':'unattractive','unbeschrieben':'unwritten / blank',
    'unterdrückt':'oppressed / suppressed','unzweifelhaft':'undoubted / unquestionable',
    'verseucht':'contaminated / infested','vorpommersch':'Western Pomeranian',
    'windgeschützt':'sheltered from wind','allgemeinverbindlich':'generally binding',
    'altertümlich':'ancient / antique','anwenderfreundlich':'user-friendly',
    'beantwortet':'answered','brillanten':'(bare stem; cf. brillant: brilliant)',
    'disziplinär':'disciplinary','emanzipatorisch':'emancipatory','gedämpft':'subdued / dampened',
    'geldpolitisch':'monetary-policy','gendergerecht':'gender-appropriate','großtechnisch':'industrial-scale',
    'interoperabel':'interoperable','meterhoch':'metres high','mundgerecht':'bite-sized',
    'naturhistorisch':'natural-history','nichtdeutsch':'non-German','normgerecht':'standard-compliant',
    'präklinisch':'preclinical','preisbewusst':'price-conscious','risikobehaftet':'risky / risk-laden',
    'selbstklebend':'self-adhesive','siebenköpfig':'seven-person','unaufhörlich':'incessant / unceasing',
    'unselbstständig':'dependent / not self-employed','untertägig':'underground / sub-daily',
    'unvorbereitet':'unprepared','vierspurig':'four-lane','abfließend':'draining / flowing off',
    'abgeschlagen':'beaten / way behind','abgeschottet':'sealed off / isolated',
    'achtwöchig':'eight-week','antizyklisch':'counter-cyclical','ausgebucht':'fully booked',
    'demokratiefeindlich':'anti-democratic','detailverliebt':'detail-oriented / detail-loving',
    'eidesstattlich':'sworn / under oath','einspurig':'single-lane','epigenetisch':'epigenetic',
    'erkennungsdienstlich':'identification-related (police)','esoterisch':'esoteric',
    'figürlich':'figurative','gerontopsychiatrisch':'geriatric-psychiatric',
    'handverlesen':'hand-picked','herzkrank':'with heart disease',
    'herzzerreißend':'heart-rending','intersektoral':'intersectoral',
    'jahrtausendealt':'thousand-year-old / millennial','knallrot':'bright red / fire-engine red',
    'kompositorisch':'compositional','langzeitarbeitslos':'long-term unemployed',
    'linksseitig':'left-sided','millionenschwer':'million-euro / multi-million',
    'multidimensional':'multidimensional','nordwestdeutsch':'northwest German',
    'organisational':'organizational','poppig':'poppy / colourful','realitätsgetreu':'true to reality',
    'russischsprachig':'Russian-speaking','schattenspendend':'shade-providing',
    'schulfrei':'no school / school-free','spannungsgeladen':'tension-filled / suspenseful',
    'stufenweise':'stepwise / gradually','tiefenpsychologisch':'depth-psychological',
    'übertariflich':'above the collective wage agreement','unbesorgt':'unconcerned',
    'unhandlich':'unwieldy','unlimitiert':'unlimited','unspektakulär':'unspectacular',
    'unversorgt':'unprovided / unmanaged','unvorteilhaft':'unflattering / disadvantageous',
    'verfeindet':'hostile / at odds','verklebt':'stuck / glued','vernichtend':'devastating',
    'wacklig':'wobbly / shaky','wissenschaftspolitisch':'science-policy','zeithistorisch':'contemporary-historical',
    'zollrechtlich':'customs-law','zweigleisig':'twin-track / dual-track',
    'abgehoben':'aloof / withdrawn','angehörig':'belonging to / member of',
    'antiviral':'antiviral','autobiographisch':'autobiographical','börsengehandelt':'exchange-traded',
    'disziplinarisch':'disciplinary','elektroakustisch':'electro-acoustic','erschaffen':'created',
    'eucharistisch':'Eucharistic','festverzinslich':'fixed-interest','frühneuzeitlich':'early-modern',
    'galant':'gallant','gebrauchsfertig':'ready to use','gegenständig':'opposite (botany)',
    'generativ':'generative','hautfreundlich':'skin-friendly','herstellerübergreifend':'cross-manufacturer',
    'holsteinisch':'Holstein','immerwährend':'eternal / perpetual','imperial':'imperial',
    'ineffektiv':'ineffective','informationell':'informational','interministeriell':'interministerial',
    'islamfeindlich':'anti-Islamic / Islamophobic','jihadistisch':'jihadist',
    'karnevalistisch':'carnival-related','klischeehaft':'clichéd','konzertant':'concert-like',
    'kostenbewusst':'cost-conscious','kostenneutral':'cost-neutral','lilafarben':'purple / lilac-coloured',
    'manipulativ':'manipulative','molekulargenetisch':'molecular-genetic','netzpolitisch':'internet-policy',
    'nuklearmedizinisch':'nuclear-medicine','oldenburgisch':'Oldenburg','parteiintern':'within the party',
    'personengebunden':'person-specific','planetarisch':'planetary','ruppig':'gruff / rough',
    'semesterbegleitend':'semester-accompanying','serologisch':'serological','summarisch':'summary / cumulative',
    'taiwanisch':'Taiwanese','tiefschwarz':'jet-black','tröstlich':'comforting',
    'überdeutlich':'extremely clear','unausgewogen':'unbalanced','ungehemmt':'unrestrained',
    'unkonzentriert':'unfocused','unmotiviert':'unmotivated','unschlüssig':'undecided',
    'westafrikanisch':'West African','zähneknirschend':'reluctantly / through gritted teeth',
    'zweispurig':'two-lane','abfallrechtlich':'waste-law','abgedreht':'crazy / wacky / wrapped (filming)',
    'amüsiert':'amused','aufgeweckt':'alert / lively','ausländerfeindlich':'xenophobic',
    'außenstehend':'outside / external','außenwirtschaftlich':'foreign-trade','ayurvedisch':'Ayurvedic',
    'befriedet':'pacified','befüllt':'filled','berufsunfähig':'unable to work / occupationally disabled',
    'betreten':'embarrassed / entered','bodentief':'floor-to-ceiling','chromatisch':'chromatic',
    'eineinhalbstündig':'1.5-hour','entnervt':'exasperated','erntefrisch':'farm-fresh',
    'fahrtüchtig':'fit to drive','feinsinnig':'subtle / refined','fragmentiert':'fragmented',
    'frauenpolitisch':'women\'s-policy','fünfmonatig':'five-month','fünfzehnjährig':'fifteen-year-old',
    'gewitzt':'shrewd / canny','gutverdienend':'high-earning','harntreibend':'diuretic',
    'hochprozentig':'high-proof','irrwitzig':'absurd / mad','kleinwüchsig':'short-statured',
    'kolorektal':'colorectal','konsularisch':'consular','kräftezehrend':'exhausting',
    'landespolitisch':'state-political','lebenserhaltend':'life-sustaining','meistgesehen':'most-watched',
    'multiethnisch':'multiethnic','nichtlinear':'nonlinear','nichtreligiös':'non-religious',
    'phonologisch':'phonological','postsowjetisch':'post-Soviet','prädiktiv':'predictive',
    'privatärztlich':'private-medical','randständig':'marginalized','rechtskonservativ':'right-conservative',
    'regennass':'rain-soaked','rückwärtsgewandt':'backward-looking','sattgrün':'lush green',
    'schadlos':'unharmed / harmless','sechsköpfig':'six-person','sechsstündig':'six-hour',
    'sechsteilig':'six-part','spanischsprachig':'Spanish-speaking','spätantik':'late-antique',
    'subtraktiv':'subtractive','symbolträchtig':'symbolic / symbol-laden','teambildend':'team-building',
    'teilnahmeberechtigt':'eligible to participate','traditionsbewusst':'traditional / tradition-conscious',
    'transgen':'transgenic','überaltert':'over-aged','übersät':'strewn / covered',
    'überschlägig':'rough / approximate','umsatzstark':'high-revenue','unausgesprochen':'unspoken',
    'unautorisiert':'unauthorized','unbeschädigt':'undamaged','unkommentiert':'uncommented',
    'unüberhörbar':'unmistakable / impossible to miss','unumwunden':'frankly / candidly',
    'unverkrampft':'relaxed / uninhibited','unverlangt':'unsolicited','unzerkaut':'unchewed',
    'verformbar':'deformable','verwaschen':'faded / washed out','viersemestrig':'four-semester',
    'vorbestraft':'with a criminal record','waagrecht':'horizontal','zweifarbig':'two-coloured',
    'zweiminütig':'two-minute','zweistöckig':'two-storey','achtköpfig':'eight-person',
    'affin':'affine / similar','ägäisch':'Aegean','allabendlich':'every evening',
    'anschmiegsam':'cuddly / clingy','apokalyptisch':'apocalyptic','arabischsprachig':'Arabic-speaking',
    'arbeitstäglich':'daily working','artverwandt':'related (species/kind)','ausnehmend':'exceedingly',
    'auszugsweise':'in extracts','batterieelektrisch':'battery-electric','berufsständisch':'professional / corporative',
    'beseelt':'imbued / soulful','bestürzt':'dismayed / shocked','bodenlang':'floor-length',
    'brandgefährlich':'extremely dangerous',
}

def main():
    p = ROOT/'data'/'adjectives.json'
    d = json.loads(p.read_text(encoding='utf-8'))
    by = {a['word']:a for a in d['adjectives']}
    f=nb=nf=0
    for w,en in ADJ.items():
        a = by.get(w)
        if not a: nf+=1; continue
        if a.get('english','').strip(): nb+=1; continue
        a['english']=en; f+=1
    p.write_text(json.dumps(d, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    print(f"  filled: {f}, already-filled: {nb}, not-in-dataset: {nf}")

if __name__=='__main__': main()
