#!/usr/bin/env python3
"""Fix English meanings for German verbs - same approach as noun/adjective cleanup."""
import json

# Corrections: German verb -> best English meaning(s)
# Guidelines: use the single most common/intuitive meaning when possible,
# 2-3 meanings only when genuinely distinct common uses exist.
VERB_CORRECTIONS = {
    # Top 100 - most critical
    'sein': 'be',
    'werden': 'become / get',
    'haben': 'have',
    'können': 'can / be able to',
    'sollen': 'should / shall',
    'geben': 'give',
    'müssen': 'must / have to',
    'finden': 'find',
    'machen': 'make / do',
    'kommen': 'come',
    'stehen': 'stand',
    'lassen': 'let / leave',
    'gehen': 'go / walk',
    'wollen': 'want',
    'bieten': 'offer',
    'liegen': 'lie / be located',
    'erhalten': 'receive / get',
    'zeigen': 'show',
    'sehen': 'see',
    'stellen': 'put / place',
    'nutzen': 'use',
    'gelten': 'apply / be valid',
    'sagen': 'say / tell',
    'dürfen': 'may / be allowed to',
    'bleiben': 'stay / remain',
    'nehmen': 'take',
    'bringen': 'bring / take',
    'anbieten': 'offer',
    'bestehen': 'exist / consist of / insist on',
    'arbeiten': 'work',
    'bekommen': 'get / receive',
    'halten': 'hold / keep / stop',
    'erreichen': 'reach / achieve',
    'stattfinden': 'take place',
    'setzen': 'put / place / set',
    'verwenden': 'use',
    'hören': 'hear / listen',
    'entstehen': 'arise / develop',
    'beginnen': 'begin / start',
    'brauchen': 'need',
    'ermöglichen': 'enable / make possible',
    'sorgen': 'ensure / worry / care',
    'befinden': 'be located',
    'fördern': 'promote / support',
    'einsetzen': 'use / deploy',
    'treffen': 'meet / hit',
    'erklären': 'explain',
    'schaffen': 'create / manage',
    'vorstellen': 'introduce / imagine',
    'durchführen': 'carry out / conduct',
    'sprechen': 'speak / talk',
    'übernehmen': 'take over / assume',
    'handeln': 'act / trade',
    'heißen': 'be called / mean',
    'benötigen': 'need / require',
    'tragen': 'carry / wear',
    'gestalten': 'design / shape',
    'gewinnen': 'win / gain',
    'verbinden': 'connect / combine',
    'enthalten': 'contain',
    'wählen': 'choose / vote / elect',
    'erwarten': 'expect',
    'fahren': 'drive / go / ride',
    'ziehen': 'pull / move',
    'dienen': 'serve',
    'verstehen': 'understand',
    'legen': 'put / lay',
    'schreiben': 'write',
    'einladen': 'invite',
    'nennen': 'call / name',
    'verfügen': 'have / possess',
    'empfehlen': 'recommend',
    'planen': 'plan',
    'aufnehmen': 'record / accept / absorb',

    # 101-200
    'kaufen': 'buy',
    'umsetzen': 'implement',
    'versuchen': 'try',
    'berichten': 'report',
    'entdecken': 'discover',
    'ändern': 'change',
    'fragen': 'ask',
    'beschäftigen': 'employ / occupy',
    'funktionieren': 'work / function',
    'beachten': 'pay attention to / observe',
    'leisten': 'accomplish / afford',
    'lesen': 'read',
    'teilnehmen': 'participate',
    'steigen': 'climb / rise',
    'aussehen': 'look / appear',
    'liefern': 'deliver / supply',
    'verlieren': 'lose',
    'richten': 'direct / aim',
    'erfüllen': 'fulfill',
    'fehlen': 'be missing / lack',
    'ergeben': 'result / yield',
    'prüfen': 'check / examine',
    'überzeugen': 'convince',
    'genießen': 'enjoy',
    'betragen': 'amount to',
    'beteiligen': 'participate / involve',
    'erhöhen': 'increase / raise',
    'sichern': 'secure / protect',
    'berücksichtigen': 'consider / take into account',
    'wünschen': 'wish / want',
    'erzählen': 'tell / narrate',
    'achten': 'pay attention to / respect',
    'beitragen': 'contribute',
    'wirken': 'have an effect / seem',
    'schließen': 'close / conclude',
    'umfassen': 'include / comprise',
    'aufbauen': 'build / build up',
    'fühlen': 'feel',
    'zahlen': 'pay',
    'abschließen': 'complete / lock / conclude',
    'ankommen': 'arrive / depend on',
    'eröffnen': 'open',
    'feststellen': 'determine / notice',
    'sammeln': 'collect / gather',
    'reichen': 'be enough / suffice',
    'auszeichnen': 'distinguish / award',
    'gründen': 'found / establish',
    'sparen': 'save',
    'anpassen': 'adapt / adjust',
    'treten': 'step / kick',
    'verkaufen': 'sell',
    'passieren': 'happen',
    'entsprechen': 'correspond to',
    'erweitern': 'expand / extend',
    'ergänzen': 'add / supplement',
    'stärken': 'strengthen',
    'warten': 'wait / maintain',
    'vertreten': 'represent',
    'organisieren': 'organize',
    'beziehen': 'refer to / obtain',
    'wachsen': 'grow',
    'angeben': 'state / indicate',
    'anzeigen': 'display / report',
    'passen': 'fit / suit',
    'bewegen': 'move',
    'dauern': 'last / take (time)',
    'kosten': 'cost / taste',
    'bezeichnen': 'describe / denote',
    'verhindern': 'prevent',
    'betreiben': 'operate / run',
    'anmelden': 'register / sign up',
    'verlassen': 'leave',
    'lohnen': 'be worth it',
    'bestellen': 'order',
    'gewährleisten': 'guarantee / ensure',
    'glauben': 'believe',
    'herstellen': 'produce / manufacture',
    'auswählen': 'choose / select',
    'lösen': 'solve / release',
    'erlauben': 'allow / permit',
    'wenden': 'turn / apply to',
    'unterscheiden': 'distinguish / differ',
    'vorsehen': 'plan / provide for',
    'bestätigen': 'confirm',
    'ausgehen': 'go out / assume',
    'einstellen': 'set / hire / stop',
    'verpflichten': 'oblige / commit',

    # 201-300
    'bezahlen': 'pay',
    'speichern': 'save / store',
    'sitzen': 'sit',
    'erinnern': 'remember / remind',
    'meinen': 'mean / think',
    'mögen': 'like / may',
    'bitten': 'ask / request',
    'erwerben': 'acquire / obtain',
    'auftreten': 'appear / occur',
    'belegen': 'prove / occupy',
    'reduzieren': 'reduce',
    'festlegen': 'determine / define',
    'gefallen': 'please / like',
    'prägen': 'shape / characterize',
    'laden': 'load / charge / invite',
    'melden': 'report',
    'betonen': 'emphasize / stress',
    'betreuen': 'take care of / look after',
    'einrichten': 'set up / furnish',
    'rechnen': 'calculate / expect',
    'teilen': 'share / divide',
    'bewerben': 'apply',
    'vornehmen': 'carry out / intend',
    'beantworten': 'answer',
    'annehmen': 'accept / assume',
    'schauen': 'look / watch',
    'eingehen': 'go into / accept',
    'beschließen': 'decide',
    'erzielen': 'achieve',
    'stammen': 'come from / originate',
    'engagieren': 'commit / employ',
    'leiten': 'lead / manage',
    'bewerten': 'evaluate / rate',
    'ersetzen': 'replace',
    'überprüfen': 'check / review',
    'erläutern': 'explain',
    'hinweisen': 'point out / indicate',
    'kümmern': 'take care of',
    'testen': 'test',
    'ausstatten': 'equip / provide',
    'beobachten': 'observe / watch',
    'ermitteln': 'determine / investigate',
    'begrüßen': 'greet / welcome',
    'verzichten': 'do without / forgo',
    'stecken': 'put / be stuck',
    'verfolgen': 'pursue / follow',
    'sicherstellen': 'ensure / guarantee',
    'ansprechen': 'address / appeal to',
    'erheben': 'raise / charge',
    'abgeben': 'hand in / give',
    'übertragen': 'transfer / broadcast',
    'wechseln': 'change / exchange',
    'produzieren': 'produce',
    'erfassen': 'record / capture',
    'fallen': 'fall',
    'erleichtern': 'make easier / facilitate',
    'benutzen': 'use',
    'betrachten': 'consider / look at',
    'holen': 'fetch / get',
    'ansehen': 'look at / watch',
    'wahrnehmen': 'perceive / notice',
    'erarbeiten': 'develop / work out',
    'regeln': 'regulate / arrange',
    'anlegen': 'create / invest',
    'buchen': 'book',
    'beantragen': 'apply for',
    'bearbeiten': 'edit / process',
    'verbringen': 'spend (time)',
    'austauschen': 'exchange / swap',
    'ausbauen': 'expand / develop',
    'ausschließen': 'exclude / rule out',
    'verleihen': 'lend / award',
    'schlagen': 'beat / hit',
    'umgehen': 'handle / avoid',
    'absolvieren': 'complete',
    'einführen': 'introduce / import',
    'verarbeiten': 'process',
    'fällen': 'fell / make (a decision)',
    'versorgen': 'supply / take care of',

    # 301-400
    'vergeben': 'forgive / award',
    'verlangen': 'demand / require',
    'vergessen': 'forget',
    'rufen': 'call / shout',
    'steigern': 'increase / improve',
    'widmen': 'dedicate',
    'vereinbaren': 'agree / arrange',
    'anfangen': 'begin / start',
    'wohnen': 'live',
    'drehen': 'turn / spin / shoot (film)',
    'klären': 'clarify',
    'löschen': 'delete / extinguish',
    'erzeugen': 'produce / generate',
    'schicken': 'send',
    'essen': 'eat',
    'aufzeigen': 'show / demonstrate',
    'vergleichen': 'compare',
    'lieben': 'love',
    'beenden': 'end / finish',
    'verdienen': 'earn / deserve',
    'vorlegen': 'present / submit',
    'sterben': 'die',
    'bereitstellen': 'provide / make available',
    'leiden': 'suffer',
    'aufstellen': 'set up / establish',
    'finanzieren': 'finance',
    'mitbringen': 'bring along',
    'greifen': 'grab / reach',
    'ausfallen': 'fail / be canceled',
    'entfernen': 'remove',
    'interessieren': 'interest',
    'nachweisen': 'prove / demonstrate',
    'beeinflussen': 'influence',
    'gebären': 'give birth',
    'zulassen': 'allow / permit',
    'anschließen': 'connect / join',
    'schätzen': 'estimate / appreciate',
    'veranstalten': 'organize / host',
    'abhängen': 'depend on',
    'orientieren': 'orient / guide',
    'versprechen': 'promise',
    'werfen': 'throw',
    'realisieren': 'realize / implement',
    'zusammenarbeiten': 'cooperate / work together',
    'begeistern': 'inspire / excite',
    'einnehmen': 'take / occupy',
    'ausprobieren': 'try out',
    'kämpfen': 'fight / struggle',
    'raten': 'advise / guess',
    'erkunden': 'explore',
    'vorkommen': 'occur / happen',
    'aufrufen': 'call / call up',
    'erteilen': 'give / issue',
    'bedienen': 'serve / operate',
    'landen': 'land',
    'lauten': 'read / say (text)',
    'pflegen': 'care for / maintain',
    'klingen': 'sound',
    'ausführen': 'carry out / execute',
    'bedürfen': 'need / require',
    'stimmen': 'be correct / vote',
    'berechnen': 'calculate / charge',
    'verletzen': 'injure / violate',
    'anwenden': 'apply / use',
    'ausreichen': 'suffice / be enough',
    'ausrichten': 'align / host',
    'zusammenstellen': 'compile / put together',
    'abstimmen': 'vote / coordinate',
    'senden': 'send / broadcast',
    'verursachen': 'cause',
    'durchsetzen': 'enforce / prevail',
    'trennen': 'separate',
    'befassen': 'deal with',
    'errichten': 'build / establish',
    'eintragen': 'enter / register',
    'erledigen': 'take care of / finish',
    'messen': 'measure',
    'ankündigen': 'announce',
    'behalten': 'keep / remember',
    'sinken': 'sink / decline',
    'anerkennen': 'acknowledge / recognize',
    'auslösen': 'trigger / cause',
    'herunterladen': 'download',
    'ausmachen': 'make up / turn off / matter',
    'tun': 'do',

    # 401-500
    'gedenken': 'commemorate',
    'verbreiten': 'spread',
    'ablehnen': 'refuse / reject',
    'verraten': 'betray / reveal',
    'konzentrieren': 'concentrate / focus',
    'reden': 'talk / speak',
    'steuern': 'control / steer',
    'basieren': 'be based on',
    'eingeben': 'enter / input',
    'senken': 'lower / reduce',
    'verweisen': 'refer / point',
    'drohen': 'threaten',
    'begegnen': 'encounter / meet',
    'herausfinden': 'find out / discover',
    'zukommen': 'approach / be due to',
    'angehen': 'concern / tackle',
    'etablieren': 'establish',
    'entnehmen': 'take from / gather',
    'hinzufügen': 'add',
    'kontrollieren': 'check / control',
    'fortsetzen': 'continue',
    'stoßen': 'push / bump into',
    'einhalten': 'comply with / observe',
    'zunehmen': 'increase / gain weight',
    'verlaufen': 'proceed / go',
    'retten': 'rescue / save',
    'verschwinden': 'disappear',
    'verabschieden': 'say goodbye / pass (a law)',
    'binden': 'bind / tie',
    'fließen': 'flow',
    'danken': 'thank',
    'merken': 'notice / remember',
    'herrschen': 'rule / prevail',
    'einbeziehen': 'include',
    'ausgeben': 'spend / issue',
    'äußern': 'express',
    'antreten': 'begin / start',
    'registrieren': 'register / notice',
    'hängen': 'hang',
    'beweisen': 'prove',
    'unterliegen': 'be subject to',
    'abdecken': 'cover',
    'füllen': 'fill',
    'auseinandersetzen': 'deal with / examine',
    'auffordern': 'request / urge',
    'auswirken': 'have an effect',
    'reisen': 'travel',
    'weitergeben': 'pass on',
    'unternehmen': 'undertake',
    'beauftragen': 'commission / hire',
    'besetzen': 'occupy / fill (a position)',
    'warnen': 'warn',
    'begründen': 'justify / establish',
    'besprechen': 'discuss',
    'fassen': 'grasp / hold',
    'verschaffen': 'provide / obtain',
    'mitnehmen': 'take along',
    'motivieren': 'motivate',
    'verlängern': 'extend / prolong',
    'festhalten': 'hold on to / record',
    'verbieten': 'forbid / prohibit',
    'währen': 'last',
    'ausbilden': 'train / educate',
    'aussprechen': 'pronounce / express',
    'drücken': 'press / push',
    'erbringen': 'provide / produce',
    'einschränken': 'restrict / limit',
    'entfallen': 'be dropped / be omitted',
    'begrenzen': 'limit',
    'benennen': 'name / designate',
    'übergeben': 'hand over',
    'verringern': 'reduce / decrease',
    'zuordnen': 'assign / classify',
    'empfangen': 'receive / welcome',
    'auffallen': 'stand out / attract attention',
    'erwähnen': 'mention',
    'schmecken': 'taste',
    'voraussetzen': 'presuppose / require',
    'beschränken': 'limit / restrict',
    'spüren': 'feel / sense',
    'anregen': 'stimulate / suggest',
    'ausstellen': 'exhibit / issue',
    'verstärken': 'strengthen / reinforce',
    'zurückkehren': 'return',
    'überraschen': 'surprise',
    'fliegen': 'fly',
    'zeichnen': 'draw',
    'auswerten': 'analyze / evaluate',
    'gebieten': 'command / demand',
    'zustimmen': 'agree',
    'schenken': 'give (as a gift)',
    'gefährden': 'endanger',
    'kennzeichnen': 'characterize / mark',
    'kündigen': 'cancel / quit / fire',
    'versehen': 'equip / provide',
    'aufheben': 'pick up / keep / abolish',

    # 501-600
    'aussetzen': 'expose / suspend',
    'ausüben': 'exercise / practice',
    'zurückgehen': 'go back / decline',
    'aufgeben': 'give up / assign',
    'abnehmen': 'lose weight / decrease / take off',
    'rücken': 'move',
    'überschreiten': 'exceed',
    'treiben': 'drive / do (sports)',
    'abrufen': 'retrieve / call up',
    'ansteigen': 'increase / rise',
    'üben': 'practice',
    'zerstören': 'destroy',
    'sperren': 'block / lock',
    'aktualisieren': 'update',
    'genügen': 'suffice / be enough',
    'formulieren': 'formulate',
    'aufgreifen': 'pick up / take up',
    'ausfüllen': 'fill in / fill out',
    'bereiten': 'prepare / cause',
    'absehen': 'foresee / refrain from',
    'trinken': 'drink',
    'verpassen': 'miss',
    'stören': 'disturb',
    'singen': 'sing',
    'verzeichnen': 'record / register',
    'verwalten': 'manage / administer',
    'vorschlagen': 'suggest / propose',
    'beurteilen': 'judge / assess',
    'wecken': 'wake / arouse',
    'beleuchten': 'illuminate / shed light on',
    'klappen': 'work (out) / fold',
    'mitmachen': 'join in / participate',
    'belasten': 'burden / charge',
    'werben': 'advertise / recruit',
    'besichtigen': 'visit / view',
    'unterhalten': 'entertain / maintain / chat',
    'vereinen': 'unite',
    'erweisen': 'prove / show',
    'transportieren': 'transport',
    'eintreten': 'enter / occur',
    'zugreifen': 'access / grab',
    'erforschen': 'research / explore',
    'ablaufen': 'expire / proceed',
    'locken': 'lure / attract',
    'vorgehen': 'proceed',
    'abbauen': 'dismantle / reduce',
    'ablegen': 'put down / take (an exam)',
    'behaupten': 'claim',
    'kritisieren': 'criticize',
    'gebrauchen': 'use',
    'vernetzen': 'network / connect',
    'erlernen': 'learn',
    'verknüpfen': 'link / connect',
    'aufführen': 'list / perform',
    'einlösen': 'redeem / cash',
    'konzipieren': 'conceive / design',
    'weiterleiten': 'forward / pass on',
    'abholen': 'pick up / collect',
    'verhalten': 'behave',
    'scheitern': 'fail',
    'zurückgreifen': 'fall back on / resort to',
    'abbilden': 'depict / map',
    'anrufen': 'call (on the phone)',
    'decken': 'cover',
    'erstrecken': 'extend / stretch',
    'wiederholen': 'repeat',
    'einsehen': 'understand / realize',
    'unterbringen': 'accommodate / house',
    'nachdenken': 'think / reflect',
    'bewahren': 'preserve / keep',
    'überwachen': 'monitor / supervise',
    'vorantreiben': 'advance / push forward',
    'einbauen': 'install / build in',
    'auftauchen': 'appear / emerge',
    'hinterlassen': 'leave behind',
    'kochen': 'cook / boil',
    'absichern': 'safeguard / secure',
    'nachgehen': 'pursue / investigate',
    'versichern': 'assure / insure',
    'bewältigen': 'cope with / manage',
    'verstecken': 'hide',
    'würdigen': 'appreciate / acknowledge',
    'feststehen': 'be certain',

    # 601-700
    'spezialisieren': 'specialize',
    'wandern': 'hike / wander',
    'blicken': 'look / glance',
    'fertigen': 'manufacture / produce',
    'verwandeln': 'transform / convert',
    'schneiden': 'cut',
    'anhören': 'listen to / sound',
    'ansetzen': 'set / schedule',
    'befragen': 'question / interview',
    'reinigen': 'clean',
    'weisen': 'point / show',
    'anstreben': 'strive for / aim at',
    'befreien': 'free / liberate',
    'überwinden': 'overcome',
    'aufhalten': 'stop / delay',
    'erlangen': 'achieve / attain',
    'bedrohen': 'threaten',
    'ausweisen': 'identify / deport',
    'beeinträchtigen': 'impair / affect',
    'vermuten': 'suspect / assume',
    'thematisieren': 'address / discuss',
    'hervorheben': 'emphasize / highlight',
    'ausgleichen': 'balance / compensate',
    'empfinden': 'feel / perceive',
    'verlegen': 'lay / relocate / misplace',
    'forschen': 'research',
    'auslegen': 'interpret / lay out',
    'einschätzen': 'assess / evaluate',
    'zwingen': 'force / compel',
    'einleiten': 'initiate / introduce',
    'versenden': 'send / ship',
    'aussuchen': 'choose / select',
    'probieren': 'try / taste',
    'beseitigen': 'remove / eliminate',
    'geraten': 'get into / turn out',
    'verbrauchen': 'consume / use up',
    'ansiedeln': 'settle',
    'verschieben': 'postpone / move',
    'auflösen': 'dissolve / resolve',
    'ableiten': 'derive',
    'springen': 'jump',
    'spenden': 'donate',
    'einkaufen': 'shop / buy',
    'abrunden': 'round off',
    'agieren': 'act / operate',
    'ausdrücken': 'express',
    'unterstreichen': 'underline / emphasize',
    'mitwirken': 'participate / collaborate',
    'bergen': 'rescue / contain',
    'anstehen': 'be pending / queue',
    'wagen': 'dare / venture',
    'erstatten': 'reimburse / report',
    'knüpfen': 'tie / make (contacts)',
    'stoppen': 'stop',
    'angehören': 'belong to',
    'meistern': 'master / overcome',
    'erneuern': 'renew',
    'auszahlen': 'pay out / be worth it',
    'zubereiten': 'prepare (food)',
    'überreichen': 'hand over / present',
    'bewirken': 'cause / bring about',
    'vorgeben': 'pretend / specify',
    'entfalten': 'unfold / develop',
    'kontaktieren': 'contact',
    'kopieren': 'copy',
    'bemühen': 'make an effort / try',
    'versetzen': 'transfer / relocate',
    'entwerfen': 'design / draft',
    'begehen': 'commit / celebrate',
    'erproben': 'test / try out',
    'herausstellen': 'turn out / emphasize',
    'hervorgehen': 'result / emerge',
    'markieren': 'mark / highlight',
    'berechtigen': 'authorize / entitle',
    'verwirklichen': 'realize / achieve',

    # 701-800
    'anziehen': 'attract / dress',
    'aufkommen': 'arise / come up',
    'beheben': 'fix / remedy',
    'bevorzugen': 'prefer',
    'sanieren': 'renovate / redevelop',
    'vorschreiben': 'prescribe / require',
    'zugehen': 'approach',
    'aufteilen': 'divide / split',
    'herausgeben': 'publish / issue',
    'berufen': 'appoint / appeal',
    'schlafen': 'sleep',
    'verbergen': 'hide / conceal',
    'vertreiben': 'drive away / distribute',
    'bedenken': 'consider',
    'ehren': 'honor',
    'vereinfachen': 'simplify',
    'entspannen': 'relax',
    'umwandeln': 'convert / transform',
    'widersprechen': 'contradict',
    'brechen': 'break',
    'beschädigen': 'damage',
    'befürchten': 'fear',
    'punkten': 'score points',
    'aufsuchen': 'visit / seek out',
    'einsteigen': 'get in / board',
    'anordnen': 'order / arrange',
    'zurückführen': 'attribute / trace back',
    'erkranken': 'fall ill',
    'absetzen': 'deduct / remove',
    'einlegen': 'insert',
    'unterzeichnen': 'sign',
    'widerspiegeln': 'reflect / mirror',
    'beschleunigen': 'accelerate',
    'überleben': 'survive',
    'berühren': 'touch',
    'erfinden': 'invent',
    'töten': 'kill',
    'abschneiden': 'cut off / perform',
    'einstufen': 'classify / categorize',
    'rechtfertigen': 'justify',
    'bewähren': 'prove itself',
    'aufbewahren': 'store / keep',
    'lachen': 'laugh',
    'auskommen': 'get by / manage',
    'kooperieren': 'cooperate',
    'losgehen': 'start / go off',
    'schießen': 'shoot',
    'servieren': 'serve',
    'bereichern': 'enrich',
    'genehmigen': 'approve / permit',
    'recherchieren': 'research / investigate',
    'tauschen': 'exchange / swap',
    'durchlaufen': 'go through / pass through',
    'hinterlegen': 'deposit',
    'nachfragen': 'inquire / follow up',
    'tanzen': 'dance',
    'schaden': 'harm / damage',
    'vertrauen': 'trust',
    'anhalten': 'stop / continue',
    'erleiden': 'suffer / sustain',
    'erschweren': 'make more difficult',
    'bekanntgeben': 'announce',
    'nachkommen': 'comply with / follow',
    'umgeben': 'surround',
    'belohnen': 'reward',
    'verurteilen': 'condemn / sentence',
    'aufhören': 'stop / cease',
    'haften': 'be liable / stick',
    'heranziehen': 'consult / use',
    'lehren': 'teach',
    'waschen': 'wash',
    'zustehen': 'be entitled to',
    'brennen': 'burn',
    'freigeben': 'release / approve',
    'bekämpfen': 'fight / combat',
    'betreten': 'enter',
    'packen': 'pack / grab',
    'schulen': 'train',
    'verteidigen': 'defend',
    'ausweiten': 'expand / extend',
    'schildern': 'describe',
    'basteln': 'do crafts / tinker',
    'nachvollziehen': 'understand / comprehend',
    'umstellen': 'switch / rearrange',
    'veranlassen': 'cause / arrange',
    'zulegen': 'gain / acquire',
    'lagern': 'store / camp',
    'verantworten': 'take responsibility for',
    'zusammenfassen': 'summarize',
    'ablösen': 'replace / relieve',
    'drucken': 'print',
    'entsorgen': 'dispose of',
    'stürzen': 'fall / overthrow',
    'überarbeiten': 'revise / rework',
    'vermissen': 'miss',

    # 801-900
    'einhergehen': 'go hand in hand with',
    'vergehen': 'pass / elapse',
    'wohlfühlen': 'feel comfortable',
    'zurückgeben': 'return / give back',
    'angreifen': 'attack',
    'einschalten': 'turn on / intervene',
    'malen': 'paint / draw',
    'einplanen': 'plan / schedule',
    'ausnehmen': 'except / take out',
    'fungieren': 'act as / function as',
    'begreifen': 'understand / comprehend',
    'anfertigen': 'produce / make',
    'schieben': 'push / shove',
    'wiederfinden': 'find again',
    'gönnen': 'not begrudge / allow',
    'verdanken': 'owe',
    'verkürzen': 'shorten',
    'backen': 'bake',
    'erobern': 'conquer',
    'implementieren': 'implement',
    'gewähren': 'grant',
    'abonnieren': 'subscribe',
    'befestigen': 'attach / fasten',
    'beherbergen': 'accommodate / house',
    'entgegennehmen': 'accept / receive',
    'fliehen': 'flee',
    'trauen': 'trust / dare / marry',
    'unterbrechen': 'interrupt',
    'zurückziehen': 'withdraw / pull back',
    'abwarten': 'wait / wait and see',
    'ausdrucken': 'print (out)',
    'ausschreiben': 'advertise / announce',
    'einschließen': 'include / lock in',
    'eintauchen': 'dive in / immerse',
    'entgehen': 'escape / miss',
    'verkünden': 'announce / proclaim',
    'einfallen': 'come to mind / occur',
    'anfühlen': 'feel',
    'befördern': 'promote / transport',
    'korrigieren': 'correct',
    'schonen': 'spare / be easy on',
    'stützen': 'support / lean on',
    'abbrechen': 'break off / cancel',
    'anrechnen': 'credit / count',
    'blockieren': 'block',
    'minimieren': 'minimize',
    'vorwerfen': 'reproach / accuse',
    'abziehen': 'subtract / withdraw',
    'hinausgehen': 'go out / exceed',
    'zurückblicken': 'look back',
    'übergehen': 'pass / skip over',
    'festsetzen': 'set / determine',
    'mischen': 'mix',
    'verstoßen': 'violate / expel',
    'ernähren': 'feed / nourish',
    'verbauen': 'block / use up (materials)',
    'wandeln': 'change / stroll',
    'einigen': 'agree / unite',
    'hinterfragen': 'question',
    'lenken': 'steer / direct',
    'sortieren': 'sort',
    'verhandeln': 'negotiate',
    'bewundern': 'admire',
    'drängen': 'push / urge',
    'vergrößern': 'enlarge / increase',
    'verschließen': 'close / lock',
    'verwöhnen': 'spoil / pamper',
    'abhalten': 'hold / prevent',
    'anbauen': 'grow / cultivate',
    'anstellen': 'employ / hire',
    'entgegenwirken': 'counteract',
    'gratulieren': 'congratulate',
    'verbleiben': 'remain',
    'erlassen': 'enact / waive',
    'fürchten': 'fear',
    'hochladen': 'upload',
    'montieren': 'install / mount',
    'auskennen': 'be familiar with',
    'fortführen': 'continue',
    'spiegeln': 'reflect / mirror',
    'träumen': 'dream',
    'auflisten': 'list',
    'erörtern': 'discuss / debate',
    'fangen': 'catch',
    'überweisen': 'transfer',
    'verdoppeln': 'double',
    'abschalten': 'turn off',
    'anführen': 'lead / cite',
    'ausliefern': 'deliver / extradite',
    'abstellen': 'turn off / park',
    'voranbringen': 'advance / move forward',
    'abheben': 'withdraw / stand out',
    'entziehen': 'withdraw / revoke',
    'fotografieren': 'photograph / take a photo',
    'ausleihen': 'borrow / lend',
    'hervorrufen': 'cause / evoke',
    'entschließen': 'decide',
    'ermutigen': 'encourage',
    'übertreffen': 'surpass / exceed',
    'verpacken': 'pack / wrap',
    'zuhören': 'listen',

    # 901-1000
    'programmieren': 'program / code',
    'darlegen': 'explain / present',
    'heiraten': 'marry',
    'widerrufen': 'revoke / cancel',
    'einlassen': 'let in / get involved in',
    'ernennen': 'appoint',
    'werten': 'rate / evaluate',
    'nachlesen': 'look up / read up on',
    'abzielen': 'aim at',
    'anweisen': 'instruct / assign',
    'bestechen': 'bribe / impress',
    'schädigen': 'damage / harm',
    'verweigern': 'refuse / deny',
    'anklicken': 'click on',
    'aufbringen': 'raise / apply',
    'versammeln': 'gather / assemble',
    'gliedern': 'structure / divide',
    'unterschätzen': 'underestimate',
    'abschaffen': 'abolish',
    'stehlen': 'steal',
    'übersteigen': 'exceed',
    'vortragen': 'present / recite',
    'ausstrahlen': 'broadcast / radiate',
    'erholen': 'recover / relax',
    'schienen': 'splint',
    'verschenken': 'give away',
    'vorlesen': 'read aloud',
    'zurücklegen': 'cover (distance) / save',
    'schwimmen': 'swim',
    'ansagen': 'announce',
    'kriegen': 'get',
    'repräsentieren': 'represent',
    'streiten': 'argue / fight',
    'abspielen': 'play (back)',
    'ausscheiden': 'drop out / be eliminated',
    'ignorieren': 'ignore',
    'umziehen': 'move / change clothes',
    'übersehen': 'overlook',
    'wiegen': 'weigh',
    'einbetten': 'embed',
    'fokussieren': 'focus',
    'kleben': 'stick / glue',
    'zuweisen': 'assign',
    'abrechnen': 'settle / bill',
    'ausbreiten': 'spread out',
    'dominieren': 'dominate',
    'eingreifen': 'intervene',
    'umbauen': 'rebuild / renovate',
    'vollziehen': 'carry out / execute',
    'aufladen': 'charge / load',
    'erbauen': 'build / construct',
    'ernten': 'harvest',
    'verständigen': 'notify / inform',
    'zusammenführen': 'bring together',
    'zusammenhängen': 'be connected / be related',
    'fressen': 'eat (animals) / devour',
    'reparieren': 'repair',
    'zugeben': 'admit',
    'pflanzen': 'plant',
    'aufpassen': 'pay attention / be careful',
    'bestreiten': 'deny / finance',
    'eintreffen': 'arrive',
    'erwirtschaften': 'generate / earn',
    'hinnehmen': 'accept / put up with',
    'überfordern': 'overwhelm',
    'tauchen': 'dive',
    'zusagen': 'accept / promise',
    'aufsetzen': 'put on / draft',
    'bestaunen': 'marvel at',
    'wiedergeben': 'reproduce / render',
    'austragen': 'deliver / host (event)',
    'einloggen': 'log in',
    'erhoffen': 'hope for',
    'zurückweisen': 'reject / refuse',
    'behindern': 'hinder / obstruct',
    'entlassen': 'dismiss / fire',
    'klagen': 'complain / sue',
    'weiterführen': 'continue',
    'anheben': 'raise / lift',
    'ankündigen': 'announce',  # duplicate of ankündigen above but doesn't matter
    'aufgehen': 'open / work out',
    'beanspruchen': 'claim / demand',
    'gucken': 'look / watch',
    'ordnen': 'arrange / organize',
    'teilhaben': 'participate / share in',
    'verbrennen': 'burn',
    'versterben': 'pass away / die',
    'ausnutzen': 'exploit / take advantage of',
    'schelten': 'scold',
    'unterziehen': 'undergo / subject to',
    'vermerken': 'note / record',
    'vorfinden': 'find',
    'reißen': 'tear / rip',
    'resultieren': 'result',

    # 1001-1500 (selective - fixing the worst ones)
    'erwischen': 'catch',
    'gegenüberstehen': 'face',
    'anreisen': 'arrive / travel (to)',
    'surfen': 'surf',
    'obliegen': 'be incumbent upon',
    'anrichten': 'cause / serve (food)',
    'einschlagen': 'hit / take (a path)',
    'anbinden': 'tie / connect',
    'aufmachen': 'open',
    'ergehen': 'be issued / fare',
    'ermorden': 'murder',
    'knacken': 'crack',
    'vermarkten': 'market',
    'abzeichnen': 'become apparent',
    'ähneln': 'resemble',
    'aufstehen': 'get up / stand up',
    'aufsteigen': 'rise / climb',
    'beruhigen': 'calm / calm down',
    'zeugen': 'testify / father',
    'bescheren': 'bring / give',
    'tippen': 'type / tap / bet',
    'verschreiben': 'prescribe',
    'nachlassen': 'decrease / let up',
    'meiden': 'avoid',
    'lüften': 'air / ventilate / reveal',
    'ärger': 'annoy',
    'ärgen': 'annoy',
    'ärgern': 'annoy',
    'promovieren': 'get a doctorate',
    'anschaffen': 'purchase / acquire',
    'befriedigen': 'satisfy',
    'schalten': 'switch / shift',
    'schöpfen': 'create / draw (water)',
    'hergeben': 'give up / hand over',
    'schälen': 'peel',
    'veräußern': 'sell',
    'anmieten': 'rent',
    'unterbreiten': 'submit / present',
    'blasen': 'blow',
    'klauen': 'steal',
    'überziehen': 'cover / overdraw',
    'mangeln': 'lack',
    'ausliegen': 'be on display',
    'nachgeben': 'give in / yield',
    'sanieren': 'renovate / redevelop',
    'überleben': 'survive',
    'deinstallieren': 'uninstall',
    'vorbeischauen': 'stop by / visit',
    'verlinken': 'link',
    'beibringen': 'teach',
    'küren': 'choose / elect',
    'enttäuschen': 'disappoint',
    'schlüpfen': 'slip / hatch',
    'zaubern': 'do magic',
    'aussteigen': 'get out / exit',
    'referieren': 'present / report',
    'durchstarten': 'take off / go for it',
    'verabschieden': 'say goodbye / pass (a law)',
    'bereithalten': 'have ready',
    'verführen': 'seduce / tempt',
    'einholen': 'catch up / obtain',
    'verschlüsseln': 'encrypt',
    'abwickeln': 'handle / process',
    'verschärfen': 'tighten / intensify',
    'zusammenschließen': 'merge / join together',
    'sanieren': 'renovate / redevelop',
    'rocken': 'rock',
    'unterdrücken': 'suppress / oppress',
    'verunsichern': 'unsettle',
    'ausschelten': 'scold',
    'wickeln': 'wrap / wind',
    'strecken': 'stretch',
    'betreten': 'enter',
    'sch': 'protect',  # in case of encoding issues
    'duften': 'smell nice',
    'hetzen': 'rush / incite',
    'schreien': 'scream / shout',
    'betrügen': 'cheat / deceive',
    'mähen': 'mow',
    'mühen': 'make an effort',
    'frühstücken': 'have breakfast',
    'hauen': 'hit',
    'wischen': 'wipe',
    'zocken': 'gamble',
    'abstürzen': 'crash',
    'streicheln': 'stroke / pet',
    'recyceln': 'recycle',
    'umlegen': 'distribute / flip (switch)',
    'thronen': 'sit enthroned',
    'braten': 'fry / roast',
    'heizen': 'heat',
    'anbraten': 'sear / brown',
    'fahnden': 'search for',
    'hüpfen': 'hop / jump',
    'firmieren': 'trade under the name',
}

# Load verb data
with open('data/verbs.json', encoding='utf-8') as f:
    data = json.load(f)

changed = 0
for verb in data['verbs']:
    word = verb['word']
    if word in VERB_CORRECTIONS:
        old = verb['english']
        new = VERB_CORRECTIONS[word]
        if old != new:
            verb['english'] = new
            changed += 1
            print(f"  {verb['rank']:4d} {word}: '{old}' -> '{new}'")

with open('data/verbs.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nFixed {changed} verb meanings.")
