#!/usr/bin/env python3
"""Fix remaining garbage auto-generated adjective translations using pattern rules."""
import json
import sys
import re

sys.stdout.reconfigure(encoding='utf-8')

# Direct fixes for all remaining garbage translations
# Format: German word -> correct English translation
FIXES = {
    # -isch words (were "X-ish/-ic")
    'atmosphärisch': 'atmospheric',
    'graphisch': 'graphic',
    'erzieherisch': 'educational/pedagogical',
    'betrügerisch': 'fraudulent/deceitful',
    'perspektivisch': 'perspective/in perspective',
    'minimalistisch': 'minimalist',
    'planerisch': 'planning-related',
    'rechtspopulistisch': 'right-wing populist',
    'sozialdemokratisch': 'social democratic',
    'musisch': 'artistic/musical',
    'futuristisch': 'futuristic',
    'gärtnerisch': 'horticultural/gardening',
    'missionarisch': 'missionary',
    'ostfriesisch': 'East Frisian',
    'schauspielerisch': 'acting/theatrical',
    'zahnmedizinisch': 'dental',
    'zeichnerisch': 'drawing/draftsmanship',
    'intensivmedizinisch': 'intensive care',
    'publizistisch': 'journalistic/media',
    'zerstörerisch': 'destructive/devastating',
    'mörderisch': 'murderous/grueling',
    'dramaturgisch': 'dramaturgical',
    'neurochirurgisch': 'neurosurgical',
    'migrantisch': 'migrant',
    'schulpsychologisch': 'school psychology',
    'ionisch': 'ionic/Ionian',
    'propagandistisch': 'propagandistic',
    'artistisch': 'acrobatic/artistic',
    'buchhalterisch': 'accounting/bookkeeping',
    'erfinderisch': 'inventive/creative',
    'idealistisch': 'idealistic',
    'kabarettistisch': 'cabaret/satirical',
    'spektroskopisch': 'spectroscopic',
    'wendisch': 'Wendish/Sorbian',
    'floristisch': 'floral/floristic',
    'notfallmedizinisch': 'emergency medical',
    'bildhauerisch': 'sculptural',
    'pantomimisch': 'pantomimic',
    'folkloristisch': 'folkloric',
    'exorzistisch': 'exorcistic',
    'feudalistisch': 'feudalistic',
    'imperialistisch': 'imperialistic',
    'expressionistisch': 'expressionist',
    'impressionistisch': 'impressionist',
    'surrealistisch': 'surrealist',
    'kubistisch': 'cubist',
    'dadaistisch': 'dadaist',
    'absolutistisch': 'absolutist',
    'nihilistisch': 'nihilistic',
    'anarchistisch': 'anarchist',
    'materialistisch': 'materialistic',
    'naturalistisch': 'naturalistic',
    'rationalistisch': 'rationalist',
    'humanistisch': 'humanistic',
    'calvinistisch': 'Calvinist',
    'hinduistisch': 'Hindu',
    'buddhistisch': 'Buddhist',
    'taoistisch': 'Taoist',
    'konfuzianisch': 'Confucian',
    'schamanistisch': 'shamanistic',
    'fatalistisch': 'fatalistic',
    'masochistisch': 'masochistic',
    'narzisstisch': 'narcissistic',
    'voyeuristisch': 'voyeuristic',
    'exhibitionistisch': 'exhibitionistic',
    'terroristisch': 'terrorist',
    'separatistisch': 'separatist',
    'nationalistisch': 'nationalistic',
    'kolonialistisch': 'colonialist',
    'kapitalistisch': 'capitalist',
    'sozialistisch': 'socialist',
    'kommunistisch': 'communist',
    'stalinistisch': 'Stalinist',
    'leninistisch': 'Leninist',
    'maoistisch': 'Maoist',
    'trotzkistisch': 'Trotskyist',
    'revisionistisch': 'revisionist',
    'reformistisch': 'reformist',
    'defätistisch': 'defeatist',
    'opportunistisch': 'opportunistic',
    'chauvinistisch': 'chauvinist',
    'militaristisch': 'militaristic',
    'pazifistisch': 'pacifist',
    'altruistisch': 'altruistic',
    'egoistisch': 'egoistic/selfish',
    'hedonistisch': 'hedonistic',
    'relativistisch': 'relativistic',
    'positivistisch': 'positivist',
    'deterministisch': 'deterministic',
    'antagonistisch': 'antagonistic',
    'synkretistisch': 'syncretic',
    'voluntaristisch': 'voluntaristic',
    'elitistisch': 'elitist',
    'pluralistisch': 'pluralistic',
    'zentralistisch': 'centralist',
    'föderalistisch': 'federalist',
    'populistisch': 'populist',
    'aktivistisch': 'activist',
    'symbolistisch': 'symbolist',
    'klassizistisch': 'classicist',
    'hellenistisch': 'Hellenistic',
    'romanistisch': 'Romance studies',
    'germanistisch': 'German studies',
    'slawistisch': 'Slavic studies',
    'orientalistisch': 'orientalist',
    'voyeuristisch': 'voyeuristic',

    # -lich words (were "X-like/-ly")
    'wirtschaftswissenschaftlich': 'economics/economic science',
    'gemeindlich': 'municipal/community',
    'freiheitlich': 'liberal/free',
    'ingenieurwissenschaftlich': 'engineering science',
    'vorbehaltlich': 'subject to/with reservation',
    'geschlechtlich': 'sexual/gender-related',
    'jahreszeitlich': 'seasonal',
    'fürstlich': 'princely/lavish',
    'textlich': 'textual',
    'klanglich': 'tonal/sound-related',
    'geisteswissenschaftlich': 'humanities',
    'herrschaftlich': 'stately/grand',
    'muttersprachlich': 'native language',
    'hochsommerlich': 'midsummer',
    'zeitgeschichtlich': 'contemporary historical',
    'begrifflich': 'conceptual',
    'eiszeitlich': 'ice age/glacial',
    'geowissenschaftlich': 'geoscientific',
    'entgeltlich': 'for a fee/paid',
    'erziehungswissenschaftlich': 'educational science',
    'geschmacklich': 'taste-related/in terms of taste',
    'gutachterlich': 'expert/appraiser',
    'vergnüglich': 'enjoyable/amusing',
    'charakterlich': 'in terms of character',
    'pfleglich': 'careful/gentle',
    'abfallwirtschaftlich': 'waste management',
    'grundgesetzlich': 'constitutional (Basic Law)',
    'heimatkundlich': 'local history',
    'heimatlich': 'homeland/homely',
    'schmerzlich': 'painful',
    'schachlich': 'chess-related',
    'widerruflich': 'revocable',
    'dinglich': 'material/in rem',
    'literaturwissenschaftlich': 'literary studies',
    'nachrichtendienstlich': 'intelligence (service)',
    'frühmittelalterlich': 'early medieval',
    'gesellschaftspolitisch': 'socio-political',
    'bildungspolitisch': 'education policy',
    'verkehrspolitisch': 'transport policy',
    'umweltpolitisch': 'environmental policy',
    'wirtschaftspolitisch': 'economic policy',
    'sicherheitspolitisch': 'security policy',
    'außenpolitisch': 'foreign policy',
    'innenpolitisch': 'domestic policy',
    'parteipolitisch': 'party political',
    'finanzpolitisch': 'fiscal policy',
    'sozialpolitisch': 'social policy',
    'kommunalpolitisch': 'municipal politics',
    'energiepolitisch': 'energy policy',
    'hochschulpolitisch': 'university policy',
    'kulturpolitisch': 'cultural policy',
    'medienpolitisch': 'media policy',
    'ordnungspolitisch': 'regulatory policy',
    'rechtspolitisch': 'legal policy',
    'sportpolitisch': 'sports policy',
    'gesundheitspolitisch': 'health policy',
    'entwicklungspolitisch': 'development policy',
    'friedenspolitisch': 'peace policy',
    'machtpolitisch': 'power politics',
    'geopolitisch': 'geopolitical',
    'realpolitisch': 'realpolitik',
    'tagespolitisch': 'current political',
    'weltpolitisch': 'world political',

    # -bar words (were "X-able")
    'erfahrbar': 'experienceable',
    'einsehbar': 'viewable/understandable',
    'faltbar': 'foldable',
    'abschließbar': 'lockable',
    'begreifbar': 'comprehensible',
    'belegbar': 'verifiable/documentable',
    'behandelbar': 'treatable',
    'reproduzierbar': 'reproducible',
    'wandelbar': 'changeable/versatile',
    'kalkulierbar': 'calculable',
    'darstellbar': 'representable/displayable',
    'durchschaubar': 'transparent/see-through',
    'ausleihbar': 'borrowable/lendable',
    'verschiebbar': 'movable/shiftable',
    'abbildbar': 'mappable/representable',
    'abspielbar': 'playable',
    'addierbar': 'addable',
    'analysierbar': 'analyzable',
    'bearbeitbar': 'editable/processable',
    'beeinflussbar': 'influenceable',
    'befüllbar': 'fillable',
    'beherrschbar': 'manageable/controllable',
    'belegbar': 'provable/verifiable',
    'benennbar': 'nameable',
    'berechenbar': 'calculable/predictable',
    'bestrafbar': 'punishable',
    'bewertbar': 'assessable',
    'dehnbar': 'stretchable/elastic',
    'drehbar': 'rotatable',
    'einklagbar': 'legally enforceable',
    'einlösbar': 'redeemable',
    'entfernbar': 'removable',
    'erdenkbar': 'conceivable',
    'erfassbar': 'recordable/detectable',
    'erschließbar': 'developable/inferable',
    'erwerbbar': 'acquirable',
    'formbar': 'malleable/formable',
    'handhabbar': 'manageable',
    'haltbar': 'durable/long-lasting',
    'korrigierbar': 'correctable',
    'kündbar': 'terminable',
    'lenkbar': 'steerable',
    'lokalisierbar': 'localizable',
    'manipulierbar': 'manipulable',
    'mietbar': 'rentable',
    'modifizierbar': 'modifiable',
    'nachprüfbar': 'verifiable',
    'nachweisbar': 'provable/detectable',
    'negierbar': 'deniable',
    'normierbar': 'standardizable',
    'operierbar': 'operable',
    'optimierbar': 'optimizable',
    'patentierbar': 'patentable',
    'quantifizierbar': 'quantifiable',
    'reduzierbar': 'reducible',
    'regelbar': 'adjustable/regulable',
    'sanierbar': 'remediable',
    'speicherbar': 'storable',
    'spaltbar': 'fissile/splittable',
    'sterilisierbar': 'sterilizable',
    'testbar': 'testable',
    'tilgbar': 'repayable',
    'transferierbar': 'transferable',
    'transportierbar': 'transportable',
    'trennbar': 'separable',
    'überbrückbar': 'bridgeable',
    'umkehrbar': 'reversible',
    'umwandelbar': 'convertible',
    'unbrauchbar': 'unusable',
    'undurchführbar': 'impracticable',
    'unermessbar': 'immeasurable',
    'unfehlbar': 'infallible',
    'unheilbar': 'incurable',
    'unlösbar': 'unsolvable',
    'unmessbar': 'immeasurable',
    'unsagbar': 'unspeakable',
    'unsichtbar': 'invisible',
    'unstillbar': 'unquenchable',
    'unteilbar': 'indivisible',
    'unveräußerbar': 'inalienable',
    'unverzichtbar': 'indispensable',
    'verwendbar': 'usable',
    'vollstreckbar': 'enforceable',
    'vorzeigbar': 'presentable',
    'zerbrechar': 'breakable/fragile',
    'zitierbar': 'quotable',

    # -ig words (were "X-y/-ish")
    'hälftig': 'half/fifty-fifty',
    'arglistig': 'malicious/deceitful',
    'sumpfig': 'swampy/marshy',
    'rissig': 'cracked',
    'adelig': 'noble/aristocratic',
    'leidig': 'tiresome/unfortunate',
    'schokoladig': 'chocolatey',
    'haltig': 'containing/lasting',
    'mehlig': 'mealy/floury',
    'schlammig': 'muddy',
    'morastig': 'marshy/boggy',
    'holprig': 'bumpy/rough',
    'klumpig': 'lumpy',
    'knusprig': 'crispy/crunchy',
    'matschig': 'muddy/mushy',
    'saftig': 'juicy',
    'seifig': 'soapy',
    'staubig': 'dusty',
    'steinig': 'rocky/stony',
    'stielig': 'stalky',
    'stoppelig': 'stubbly',
    'struppig': 'scruffy/shaggy',
    'strähnig': 'stringy',
    'wackelig': 'wobbly/shaky',
    'wässrig': 'watery',
    'wolkig': 'cloudy',
    'würzig': 'spicy/aromatic',
    'zackig': 'jagged/brisk',
    'zäh': 'tough/tenacious',
    'zottelig': 'shaggy',
    'zugig': 'drafty',
    'diesig': 'hazy/misty',
    'dumpfig': 'musty',
    'durstig': 'thirsty',
    'fettig': 'greasy/fatty',
    'flockig': 'fluffy',
    'frostig': 'frosty',
    'grasig': 'grassy',
    'griffig': 'grippy/catchy',
    'gruselig': 'creepy/spooky',
    'harzig': 'resinous/sluggish',
    'kratzig': 'scratchy',
    'kreidig': 'chalky',
    'krümelig': 'crumbly',
    'modrig': 'musty/moldy',
    'moosig': 'mossy',
    'muffig': 'musty/stuffy',
    'neblig': 'foggy/misty',
    'nieselig': 'drizzly',
    'pelzig': 'furry/fuzzy',
    'pickelig': 'pimply',
    'pudrig': 'powdery',
    'rostig': 'rusty',
    'rußig': 'sooty',
    'sandig': 'sandy',
    'schaumig': 'foamy/frothy',
    'schimmelig': 'moldy',
    'schleierhaft': 'mysterious/baffling',
    'schmalzig': 'cheesy/schmaltzy',
    'schwammig': 'spongy/vague',
    'schwefelig': 'sulfurous',
    'schwülig': 'sultry/muggy',
    'sehnig': 'sinewy',
    'speckig': 'greasy/lardy',
    'torfig': 'peaty',
    'trügerisch': 'deceptive/misleading',
    'windig': 'windy',

    # -artig words (were "-like/mannered X")
    'stichprobenartig': 'random/by sampling',
    'mengenmäßig': 'in terms of quantity',
    'explosionsartig': 'explosive',
    'vorschriftsmäßig': 'according to regulations',
    'altersmäßig': 'in terms of age',

    # Misc remaining
    'menschenfeindlich': 'misanthropic/hostile',
}


def main():
    with open('data/adjectives.json', 'r', encoding='utf-8') as f:
        data = json.load(f)

    adjs = data['adjectives']
    fixed = 0

    for a in adjs:
        word = a['word']
        eng = a.get('english', '') or ''

        if word in FIXES:
            if not eng.strip() or is_garbage(eng):
                a['english'] = FIXES[word]
                fixed += 1

    # Count remaining
    still_garbage = 0
    still_empty = 0
    for a in adjs:
        eng = a.get('english', '') or ''
        if not eng.strip():
            still_empty += 1
        elif is_garbage(eng):
            still_garbage += 1

    print(f'Fixed {fixed} translations')
    print(f'Remaining: {still_empty} empty, {still_garbage} garbage')

    data['adjectives'] = adjs
    with open('data/adjectives.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print('Saved adjectives.json')


def is_garbage(eng):
    if not eng or not eng.strip():
        return True
    patterns = [
        r'-y/-ish$',
        r'-ish/-ic$',
        r'-like/-ly$',
        r'^-like/',
        r'-like/mannered',
        r'-like/moderate',
    ]
    for p in patterns:
        if re.search(p, eng):
            return True
    # -able with dash
    if re.search(r'\w+-able$', eng):
        return True
    return False


if __name__ == '__main__':
    main()
