#!/usr/bin/env python3
"""Fix adjective meanings for rank 500-1000."""
import json

FIXES = {
    'ehrlich': 'honest',
    'illegal': 'illegal',
    'thematisch': 'thematic',
    'fundiert': 'well-founded/sound',
    'gelegentlich': 'occasional',
    'mündlich': 'oral/verbal',
    'jahrelang': 'for years',
    'scheinbar': 'apparently/seemingly',
    'vermeintlich': 'alleged/supposed',
    'scharf': 'sharp/spicy',
    'locker': 'loose/relaxed',
    'solide': 'solid/sound',
    'dementsprechend': 'accordingly/corresponding',
    'gemäß': 'in accordance with',
    'umgekehrt': 'opposite/reversed',
    'lustig': 'funny',
    'robust': 'robust/sturdy',
    'unverzüglich': 'immediate',
    'feierlich': 'festive/solemn',
    'grob': 'coarse/rough',
    'vorübergehend': 'temporary',
    'aufwendig': 'elaborate/costly',
    'ausgeprägt': 'distinct/pronounced',
    'friedlich': 'peaceful',
    'vollkommen': 'complete/perfect',
    'mächtig': 'powerful/mighty',
    'repräsentativ': 'representative',
    'nutzbar': 'usable',
    'reibungslos': 'smooth',
    'anschaulich': 'vivid/clear',
    'kompliziert': 'complicated',
    'erhalten': 'preserved',
    'heftig': 'intense/severe',
    'gewöhnlich': 'ordinary/usual',
    'sanft': 'gentle/soft',
    'beschrieben': 'described',
    'auffällig': 'conspicuous/noticeable',
    'zügig': 'swift/quick',
    'leistungsfähig': 'capable/efficient',
    'vorsichtig': 'careful/cautious',
    'schmal': 'narrow',
    'definitiv': 'definite/definitely',
    'schlimm': 'bad/serious',
    'zeitgemäß': 'modern/up-to-date',
    'organisch': 'organic',
    'pauschal': 'flat-rate/general',
    'empirisch': 'empirical',
    'feucht': 'damp/moist',
    'gespannt': 'excited/tense',
    'neuartig': 'novel/new',
    'ernsthaft': 'serious/earnest',
    'zufällig': 'random/accidental',
    'unsicher': 'uncertain/unsafe',
    'unverzichtbar': 'essential/indispensable',
    'geprägt': 'shaped/characterized',
    'arabisch': 'Arabic/Arab',
    'edel': 'noble/precious',
    'unverbindlich': 'non-binding',
    'arm': 'poor',
    'empfindlich': 'sensitive',
    'zeitgleich': 'simultaneous',
    'gerichtlich': 'judicial/court',
    'leise': 'quiet/soft',
    'sachlich': 'factual/objective',
    'erwachsen': 'adult/grown-up',
    'gemeinschaftlich': 'collective/joint',
    'geheim': 'secret',
    'still': 'quiet/silent',
    'befindlich': 'located',
    'flüssig': 'liquid/fluent',
    'fröhlich': 'cheerful/happy',
    'gleichmäßig': 'even/regular',
    'einstimmig': 'unanimous',
    'mutig': 'brave/courageous',
    'unerwünscht': 'unwanted/undesirable',
    'satt': 'full/saturated',
    'schwerwiegend': 'serious/severe',
    'anstrengend': 'exhausting/demanding',
    'unverändert': 'unchanged',
    'bar': 'cash/bare',
    'blind': 'blind',
    'böse': 'angry/evil',
    'gewaltig': 'enormous/immense',
    'traurig': 'sad',
    'bürgerlich': 'civic/civil/bourgeois',
    'seelisch': 'emotional/psychological',
    'ausgiebig': 'extensive/thorough',
    'gepflegt': 'well-maintained/neat',
    'durchgängig': 'consistent/continuous',
    'fleißig': 'diligent/hardworking',
    'eingehend': 'detailed/thorough',
    'fehlerhaft': 'faulty/flawed',
    'bemerkenswert': 'remarkable/noteworthy',
    'froh': 'glad/happy',
    'jugendlich': 'youthful/young',
    'schwanger': 'pregnant',
    'umstritten': 'controversial/disputed',
    'angepasst': 'adapted/adjusted',
    'geringfügig': 'minor/slight',
    'begehrt': 'sought-after/popular',
    'hinreichend': 'sufficient/adequate',
    'geboren': 'born',
    'gebürtig': 'native',
    'klug': 'clever/smart',
    'aufrecht': 'upright/honest',
    'geschickt': 'skillful/deft',
    'zivil': 'civil/civilian',
    'regelrecht': 'downright/proper',
    'leiblich': 'biological/physical',
    'anfänglich': 'initial',
    'sämtlich': 'all/entire',
    'clever': 'clever/smart',
    'witzig': 'funny/witty',
    'unbefristet': 'permanent/unlimited',
    'seriös': 'reputable/serious',
    'verrückt': 'crazy/mad',
    'benachteiligt': 'disadvantaged',
    'braun': 'brown',
    'strahlend': 'radiant/bright',
    'weitestgehend': 'largely/mostly',
    'erholsam': 'relaxing/restful',
    'originell': 'original/creative',
    'glatt': 'smooth',
    'mild': 'mild/gentle',
    'verstorben': 'deceased',
    'beachtlich': 'considerable/remarkable',
    'tatkräftig': 'energetic/active',
}

with open('data/adjectives.json', encoding='utf-8') as f:
    data = json.load(f)

changed = 0
for adj in data['adjectives']:
    word = adj['word']
    if word in FIXES:
        old = adj['english']
        new = FIXES[word]
        if old != new:
            adj['english'] = new
            changed += 1
            print(f"  {adj['rank']:4d} {word}: '{old}' -> '{new}'")

with open('data/adjectives.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nFixed {changed} adjective meanings (rank 500-1000).")
