#!/usr/bin/env python3
"""Second pass: fix remaining verb meanings in 1000-2000 range."""
import json

CORRECTIONS = {
    'notieren': 'note / write down',
    'mitspielen': 'play along / cooperate',
    'entführen': 'kidnap / abduct',
    'neigen': 'tend / incline',
    'räumen': 'clear / vacate',
    'aufbrechen': 'break open / set off',
    'aufzeichnen': 'record',
    'ausrüsten': 'equip',
    'beschaffen': 'obtain / procure',
    'auflegen': 'hang up / put on',
    'einteilen': 'divide / classify',
    'offenbaren': 'reveal',
    'bewilligen': 'approve / grant',
    'fertigstellen': 'complete / finish',
    'überstehen': 'survive / get through',
    'vorbeikommen': 'come by / pass by',
    'zurückkommen': 'come back / return',
    'missen': 'miss / do without',
    'wundern': 'surprise / wonder',
    'anstoßen': 'initiate / clink glasses',
    'besorgen': 'get / obtain',
    'glänzen': 'shine / excel',
    'antreffen': 'find / encounter',
    'automatisieren': 'automate',
    'beabsichtigen': 'intend',
    'kehren': 'sweep / turn',
    'anmerken': 'note / remark',
    'formen': 'form / shape',
    'aussagen': 'state / testify',
    'begehren': 'desire',
    'betätigen': 'operate / activate',
    'ruhen': 'rest',
    'verdrängen': 'displace / suppress',
    'festigen': 'strengthen / consolidate',
    'kürzen': 'shorten / reduce',
    'putzen': 'clean',
    'verschlechtern': 'worsen / deteriorate',
    'bescheinigen': 'certify / confirm',
    'verfallen': 'expire / decay',
    'bekräftigen': 'confirm / reaffirm',
    'festnehmen': 'arrest',
    'rüsten': 'arm / prepare',
    'rühren': 'stir / move',
    'absagen': 'cancel',
    'ausarbeiten': 'work out / develop',
    'ausbrechen': 'break out / escape',
    'aufspüren': 'track down',
    'besiegen': 'defeat',
    'koppeln': 'connect / couple',
    'deuten': 'interpret / point to',
    'unterstellen': 'assume / subordinate',
    'vollenden': 'complete',
    'beitreten': 'join',
    'absprechen': 'arrange / deny',
    'jagen': 'hunt / chase',
    'loslegen': 'get started',
    'prognostizieren': 'predict / forecast',
    'übereinstimmen': 'agree / correspond',
    'ausweichen': 'avoid / dodge',
    'herbeiführen': 'bring about / cause',
    'spritzen': 'spray / inject',
    'synchronisieren': 'synchronize',
    'auspacken': 'unpack',
    'befürworten': 'advocate / support',
    'erschüttern': 'shake / shatter',
    'lüften': 'air / ventilate',
    'abwehren': 'fend off / defend',
    'untermauern': 'substantiate / underpin',
    'versäumen': 'miss / neglect',
    'aufwerten': 'upgrade / enhance',
    'errechnen': 'calculate',
    'zusammenschließen': 'merge / join together',
    'wertschätzen': 'appreciate / value',
    'engagieren': 'engage / hire',
    'skalieren': 'scale',
    'säumen': 'line / delay',
    'immatrikulieren': 'enroll / matriculate',
    'obliegen': 'be the responsibility of',
    'ansetzen': 'schedule / set',
    'mähen': 'mow',

    # Obvious bad translations
    'nützen': 'be useful',
    'einhergehen': 'go hand in hand with',
    'zusammenhängen': 'be connected / be related',
    'überfordern': 'overwhelm',
    'bestaunen': 'marvel at',
    'ausschelten': 'scold',
    'vorbeischauen': 'stop by / drop in',
    'beibringen': 'teach',
    'küren': 'choose / elect',
    'enttäuschen': 'disappoint',
    'schlüpfen': 'slip / hatch',
    'referieren': 'present / report',
    'durchstarten': 'take off / launch',
    'verführen': 'seduce / tempt',
    'einholen': 'catch up / obtain',
    'verschlüsseln': 'encrypt',
    'abwickeln': 'handle / process',
    'verschärfen': 'tighten / intensify',
    'unterdrücken': 'suppress / oppress',
    'verunsichern': 'unsettle',
    'duften': 'smell nice',
    'hetzen': 'rush / incite',
    'abstürzen': 'crash',
    'recyceln': 'recycle',
    'umlegen': 'distribute / flip (switch)',
    'thronen': 'sit enthroned',
    'firmieren': 'trade under the name',

    # Fixing wordy/odd entries from 1200-2000
    'anschlagen': 'post / strike',
    'auflaufen': 'run up / accumulate',
    'eingeben': 'enter / input',
    'mitbekommen': 'notice / receive',
    'einwerben': 'raise (funds)',
    'bescheren': 'bring / give (as a gift)',
    'schalten': 'switch',
    'aussteigen': 'get off / exit',
    'promovieren': 'get a doctorate',
    'anschaffen': 'acquire',
    'verschreiben': 'prescribe',
    'hergeben': 'give up',
    'tummeln': 'romp / hurry',
    'vorbeigehen': 'pass by / go past',
    'losfahren': 'set off / depart',
    'aufspielen': 'show off',
    'aufwärmen': 'warm up',
    'deinstallieren': 'uninstall',
    'gastieren': 'perform as a guest',
    'verkleiden': 'disguise / dress up',
    'verschlagen': 'cunning / end up',
    'loswerden': 'get rid of',
    'überholen': 'overtake / overhaul',
    'anbraten': 'sear / brown',
    'schlummern': 'slumber / doze',
    'klarkommen': 'manage / cope',
    'résümieren': 'summarize',
    'resümieren': 'summarize',
    'stöbern': 'browse / rummage',
    'ahnden': 'punish / penalize',
    'dotieren': 'endow',
    'verlinken': 'link',
    'zaubern': 'do magic',
    'spinnen': 'be crazy / spin',
    'vorkehren': 'take precautions',

    # Fix awkwardly long entries
    'ansetzen': 'schedule / set',
    'wertschätzen': 'appreciate / value',
    'gönnen': 'not begrudge / allow',
    'bereithalten': 'have ready',
    'ausstatten': 'equip / provide',

    # Fix weirdly wrong translations
    'fressen': 'eat (animals) / devour',
    'schwimmen': 'swim',
    'malen': 'paint / draw',
    'blasen': 'blow',
    'klauen': 'steal',
    'überziehen': 'cover / overdraw',
    'mangeln': 'lack',
    'ausliegen': 'be on display',
    'nachgeben': 'give in / yield',
    'streicheln': 'stroke / pet',
    'braten': 'fry / roast',
    'heizen': 'heat',
    'fahnden': 'search for',
    'hüpfen': 'hop / jump',
    'wischen': 'wipe',
    'zocken': 'gamble',
    'hauen': 'hit',
    'schreien': 'scream / shout',
    'betrügen': 'cheat / deceive',
    'frühstücken': 'have breakfast',
    'befriedigen': 'satisfy',
    'schöpfen': 'create / draw (water)',
    'schälen': 'peel',
    'veräußern': 'sell',
    'anmieten': 'rent',
    'unterbreiten': 'submit / present',
}

with open('data/verbs.json', encoding='utf-8') as f:
    data = json.load(f)

changed = 0
for verb in data['verbs']:
    word = verb['word']
    if word in CORRECTIONS:
        old = verb['english']
        new = CORRECTIONS[word]
        if old != new:
            verb['english'] = new
            changed += 1
            print(f"  {verb['rank']:4d} {word}: '{old}' -> '{new}'")

with open('data/verbs.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nSecond pass: fixed {changed} more verb meanings.")
