#!/usr/bin/env python3
"""
Fix English meanings for German vocabulary game.
Rules:
- Use the single best, most common English translation
- Only include 2-3 meanings if they are genuinely distinct and commonly used
- Never include obscure, archaic, or overly technical translations
- For dual-gender nouns, provide the best meaning for each article+noun combo
"""
import json
import sys
import os

# ============================================================
# NOUN CORRECTIONS: { "word": "corrected english" }
# Only entries that need changing are listed.
# ============================================================
NOUN_CORRECTIONS = {
    # Top 100
    "Jahr": "year",
    "Kind": "child",
    "Mensch": "person/human",
    "Unternehmen": "company/enterprise",
    "Zeit": "time",
    "Tag": "day",
    "Thema": "topic/subject",
    "Stadt": "city/town",
    "Frage": "question",
    "Bereich": "area/field",
    "Arbeit": "work/job",
    "Schule": "school",
    "Möglichkeit": "possibility/opportunity",
    "Uhr": "clock/watch",
    "Frau": "woman/wife",
    "Datum": "date",
    "Beispiel": "example",
    "Land": "country/land",
    "Seite": "page/side",
    "Angebot": "offer/selection",
    "Schüler": "student/pupil",
    "Teil": "part/piece",
    "Rahmen": "frame/framework",
    "Kunde": "customer/client",
    "Ziel": "goal/destination",
    "Weg": "way/path",
    "Woche": "week",
    "Mitarbeiter": "employee/colleague",
    "Ort": "place/location",
    "Welt": "world",
    "Verfügung": "disposal/decree",
    "Fall": "case/fall",
    "Aufgabe": "task/assignment",
    "Ergebnis": "result/outcome",
    "Problem": "problem",
    "Art": "kind/type/species",
    "Bild": "picture/image",
    "Platz": "place/square/seat",
    "Veranstaltung": "event",
    "Programm": "program/programme",
    "Grund": "reason/ground",
    "Jugendlicher": "young person/teenager",
    "Region": "region",
    "Geschichte": "history/story",
    "Einsatz": "use/deployment/commitment",
    "Zukunft": "future",
    "Preis": "price/prize",
    "Regel": "rule",
    "Haus": "house/home",
    "Stelle": "position/place/job",
    "Gruppe": "group",
    "Mann": "man/husband",
    "Raum": "room/space",
    "Schülerin": "female student/pupil",
    "Leistung": "performance/achievement",
    "Stunde": "hour/lesson",
    "Blick": "look/glance/view",
    "Ausbildung": "training/education",
    "Gerät": "device/appliance",
    "Beitrag": "contribution/article",
    "Maßnahme": "measure/action",
    "Mal": "time/occasion",
    "Inhalt": "content/contents",
    "Internet": "internet",
    "Lösung": "solution/answer",
    "System": "system",
    "Rolle": "role/part",
    "Geld": "money",
    "Interesse": "interest",
    "Gesellschaft": "society/company",
    "Einrichtung": "facility/institution",
    "Buch": "book",
    "Partner": "partner",
    "Gast": "guest/visitor",
    "Straße": "street/road",
    # Top 200
    "Form": "form/shape",
    "Höhe": "height/altitude",
    "Schritt": "step",
    "Betrieb": "business/operation",
    "Spiel": "game/play",
    "Wert": "value/worth",
    "Zahl": "number",
    "Arzt": "doctor/physician",
    "Bildung": "education/formation",
    "Besucher": "visitor",
    "Film": "film/movie",
    "Zusammenarbeit": "cooperation/collaboration",
    "Anfang": "beginning/start",
    "Markt": "market",
    "Klasse": "class/grade",
    "Medium": "medium/media",
    "Entscheidung": "decision",
    "Folge": "consequence/episode",
    "Grundlage": "basis/foundation",
    "Verein": "club/association",
    "Punkt": "point/dot",
    "Chance": "chance/opportunity",
    "Bedeutung": "meaning/importance",
    "Tier": "animal",
    "Funktion": "function",
    "Kultur": "culture",
    "Prozess": "process/trial",
    "Beginn": "beginning/start",
    "Konzept": "concept/draft",
    "Ausstellung": "exhibition",
    "Herr": "man/gentleman/Mr.",
    "Anlage": "facility/attachment/investment",
    "Lage": "situation/location",
    "Engagement": "commitment/engagement",
    "Bürger": "citizen",
    "Alter": "age",
    "Aktion": "campaign/action",
    "Text": "text",
    "Wald": "forest/woods",
    "Schwerpunkt": "focus/priority",
    "Politik": "politics/policy",
    "Foto": "photo",
    "Umgang": "dealing/handling",
    "Hinweis": "hint/note/reference",
    "Schutz": "protection",
    "Kooperation": "cooperation",
    "Behandlung": "treatment",
    "Beruf": "profession/job",
    "Spaß": "fun",
    "Stiftung": "foundation",
    "Tipp": "tip/hint",
    "Dienst": "service/duty",
    "Smartphone": "smartphone",
    "Alltag": "everyday life",
    # Top 300
    "Abschluss": "degree/conclusion/completion",
    "Stand": "state/level/booth",
    "Verbindung": "connection/link",
    "Hersteller": "manufacturer",
    "Grenze": "border/boundary/limit",
    "Meter": "meter/metre",
    "Zusammenhang": "connection/context",
    "Sache": "thing/matter",
    "Wunsch": "wish/desire",
    "Tätigkeit": "activity/work",
    "Auge": "eye",
    "Kraft": "power/force/strength",
    "Gebiet": "area/field/territory",
    "Gesetz": "law",
    "Vortrag": "lecture/presentation",
    "Menge": "amount/quantity",
    "Prüfung": "exam/test/examination",
    "Änderung": "change/modification",
    "Lehrer": "teacher",
    "Mittel": "means/resources",
    "Unterricht": "lessons/instruction",
    "Zentrum": "center/centre",
    "Termin": "appointment/deadline",
    "Abend": "evening",
    "Umgebung": "surroundings/area",
    "Bank": "bank/bench",
    "Basis": "basis/base",
    "Mitte": "middle/center",
    "Untersuchung": "investigation/examination",
    "Körper": "body",
    "Zugang": "access",
    "Satz": "sentence/set/rate",
    "Nähe": "proximity/vicinity",
    "Farbe": "color/colour/paint",
    "Kollege": "colleague",
    "Anteil": "share/portion",
    "Sport": "sport",
    "Vielfalt": "diversity/variety",
    "Fläche": "area/surface",
    "Wissenschaft": "science",
    "Regelung": "regulation/arrangement",
    "Kommune": "municipality",
    "Staat": "state/country",
    "Institut": "institute",
    "Austausch": "exchange",
    "Veränderung": "change",
    "Größe": "size",
    "Ausgabe": "edition/issue/expenditure",
    "Planung": "planning",
    "Vertrag": "contract/agreement",
    "Bund": "federation/federal government",
    "Teilnahme": "participation",
    "Vater": "father",
    "Freitag": "Friday",
    "Begriff": "term/concept",
    "Test": "test",
    "Sicht": "view/perspective",
    "Kreis": "circle/district",
    "Werk": "work/factory/plant",
    "Garten": "garden",
    "Reihe": "row/series",
    "Boden": "floor/ground/soil",
    "Auftrag": "order/commission/assignment",
    "Unterschied": "difference",
    "Milliarde": "billion",
    "Karte": "card/map/ticket",
    "Behörde": "authority/agency",
    "Nachricht": "message/news",
    "Pflege": "care/nursing",
    "Branche": "industry/sector",
    "Krankenhaus": "hospital",
    "Mädchen": "girl",
    "Gutschein": "voucher/coupon",
    "Kopf": "head",
    "Marke": "brand/mark",
    "Zeitraum": "period/time span",
    "Bewegung": "movement/exercise",
    "Bundesland": "federal state",
    "Gott": "God/god",
    "Wirkung": "effect/impact",
    "Ausland": "abroad/foreign countries",
    "Reise": "trip/journey/travel",
    "Kenntnis": "knowledge",
    "Gericht": "court/dish",
    "Verband": "association/bandage",
    "Bezug": "reference/cover",
    "Schaden": "damage/harm",
    "Urlaub": "holiday/vacation",
    "Motto": "motto",
    "Führung": "leadership/guided tour",
    "Klinik": "clinic/hospital",
    "Lernen": "learning",
    "Vertreter": "representative",
    "Band": "volume/ribbon",
    "Kilometer": "kilometer",
    "Browser": "browser",
    "Flüchtling": "refugee",
    "Versorgung": "supply/care",
    "Bewertung": "rating/assessment",
    "Praktikum": "internship",
    "Linie": "line",
    "Fähigkeit": "ability/skill",
    "Bedingung": "condition/requirement",
    "Gefühl": "feeling/emotion",
    "Ansatz": "approach",
    "Start": "start",
    "Seminar": "seminar",
    "Einführung": "introduction",
    "Gestaltung": "design/arrangement",
    "Vielzahl": "multitude/large number",
    "Autor": "author",
    "Ebene": "level/plane",
    "Stimme": "voice/vote",
    "Feld": "field",
    "Angst": "fear/anxiety",
    "Hälfte": "half",
    "Lebensmittel": "food/groceries",
    "Zimmer": "room",
    "Gelegenheit": "opportunity/occasion",
    "Aufnahme": "recording/admission/photo",
    "Fehler": "mistake/error",
    "Baum": "tree",
    "Trend": "trend",
    "Meinung": "opinion",
    "Position": "position",
    "Bestandteil": "component/part",
    "Verwendung": "use/usage",
    "Sitzung": "meeting/session",
    "Strom": "electricity/current/stream",
    "Auswirkung": "effect/impact",
    "Krankheit": "illness/disease",
    "Fahrt": "journey/ride/trip",
    "Verbraucher": "consumer",
    "Mittelpunkt": "center/focus",
    "Dienstleistung": "service",
    "Angehöriger": "relative/family member",
    "Ernährung": "nutrition/diet",
    "Erkenntnis": "insight/finding",
    "Plan": "plan",
    "Geschäft": "shop/business/deal",
    "Haushalt": "household/budget",
    "Arbeitsplatz": "workplace/job",
    "Schloss": "castle/lock",
    "Ansprechpartner": "contact person",
    "Gymnasium": "grammar school/high school",
    "Sitz": "seat/headquarters",
    "Station": "station/ward",
    "Freude": "joy/pleasure",
    "Öffentlichkeit": "public",
    "Spieler": "player",
    "Maschine": "machine",
    "Fuß": "foot",
    "Rat": "advice/council",
    "Küche": "kitchen/cuisine",
    "Fachkraft": "specialist/skilled worker",
    "Vorschlag": "suggestion/proposal",
    "Anfrage": "inquiry/request",
    "Leitung": "management/line/pipe",
    "Studiengang": "degree program/course",
    "Kurs": "course/rate",
    "Jugend": "youth",
    "Handel": "trade/commerce",
    "Ware": "goods/product",
    "Vorstellung": "idea/presentation/performance",
    "Ablauf": "process/sequence/procedure",
    "Einstellung": "attitude/setting/hiring",
    "Gewalt": "violence/power",
    "Erlebnis": "experience",
    "Präsident": "president",
    "Runde": "round",
    "Bau": "construction/building",
    # Top 500 continued
    "Beziehung": "relationship",
    "Risiko": "risk",
    "Abteilung": "department",
    "Aufbau": "structure/construction",
    "Anschluss": "connection",
    "Bus": "bus",
    "Vergangenheit": "past",
    "Geschäftsführer": "managing director",
    "Zustand": "condition/state",
    "Rechnung": "bill/invoice",
    "Insel": "island",
    "Mitarbeiterin": "female employee/colleague",
    "Herbst": "autumn/fall",
    "Glück": "luck/happiness",
    "Kontrolle": "control/check",
    "Hund": "dog",
    "Messe": "trade fair/mass",
    "Erde": "earth/ground/soil",
    "Publikum": "audience/public",
    "Ursache": "cause",
    "Vorhaben": "plan/intention",
    "Theater": "theater/theatre",
    "Haut": "skin",
    "Verhältnis": "relationship/ratio",
    "Vorgabe": "guideline/requirement",
    "Umfeld": "environment/surroundings",
    "Strecke": "route/distance/stretch",
    "Büro": "office",
    "Personal": "staff/personnel",
    "Anlass": "occasion/reason",
    "Mannschaft": "team/crew",
    "Unterlage": "document/pad",
    "Bewohner": "resident/inhabitant",
    "Absatz": "paragraph/heel/sales",
    "Leiter": "head/leader/director",
    "Versicherung": "insurance",
    "Landwirtschaft": "agriculture/farming",
    "Umstand": "circumstance",
    "Faktor": "factor",
    "Maß": "measure/degree",
    "Sorge": "worry/concern",
    "Verhalten": "behavior/behaviour",
    "Urteil": "judgment/verdict",
    "Aussage": "statement",
    "Bahn": "train/railway/track",
    "Jahrzehnt": "decade",
    "Krankenkasse": "health insurance",
    "Essen": "food/meal",
    "Werbung": "advertising",
    "Grad": "degree",
    "Atmosphäre": "atmosphere",
    "Grundschule": "primary school/elementary school",
    "Druck": "pressure/print",
    "Heimat": "home/homeland",
    "Darstellung": "representation/depiction",
    "Umfang": "extent/scope",
    "Zielgruppe": "target audience/target group",
    "Dauer": "duration",
    "Anzeige": "advertisement/display/report",
    "Internetseite": "website",
    "Medikament": "medication/medicine",
    "Verständnis": "understanding",
    "Wetter": "weather",
    "Lehre": "teaching/apprenticeship",
    "Zeichen": "sign/character/symbol",
    "Bühne": "stage",
    "Ausflug": "excursion/outing",
    "Richtlinie": "guideline/directive",
    "Pflicht": "duty/obligation",
    "Abstand": "distance/gap",
    "Bürgermeister": "mayor",
    "Träger": "carrier/provider/beam",
    "Anregung": "suggestion/stimulation",
    "Eigenschaft": "property/characteristic",
    "Ausstattung": "equipment/furnishing",
    "Bürgerin": "female citizen",
    "Forderung": "demand/claim",
    "Ausbau": "expansion/development",
    "Nachfrage": "demand/inquiry",
    "Handy": "cell phone/mobile phone",
    "Zweck": "purpose",
    "Gegenstand": "object/subject",
    "Dialog": "dialogue",
    "Sonne": "sun",
    "Händler": "dealer/trader",
    "Meer": "sea/ocean",
    "Vorstand": "board of directors/executive board",
    "Handeln": "action/acting",
    "Gesicht": "face",
    "Ruhe": "peace/quiet/calm",
    "Holz": "wood",
    "Stoff": "material/fabric/substance",
    "Stärke": "strength/starch",
    "Anliegen": "concern/request",
    "Vertrauen": "trust/confidence",
    "Verkehr": "traffic/transport",
    "Übersicht": "overview",
    "Zeitung": "newspaper",
    "Beteiligung": "participation/involvement",
    "Ereignis": "event/occurrence",
    "Wand": "wall",
    "Verkauf": "sale",
    "Tochter": "daughter",
    "Gewinn": "profit/gain",
    "Opfer": "victim/sacrifice",
    "Erinnerung": "memory/reminder",
    "Fan": "fan",
    "Feuerwehr": "fire department/fire brigade",
    "Unfall": "accident",
    "Zug": "train/move/trait",
    "Lust": "desire/pleasure",
    "Gegensatz": "contrast/opposite",
    "Vorschrift": "regulation/rule",
    "Anerkennung": "recognition/appreciation",
    "Aufenthalt": "stay",
    "Schreiben": "letter/writing",
    "Belastung": "burden/strain",
    "Papier": "paper",
    "Umsatz": "revenue/turnover",
    "Agentur": "agency",
    "Aufwand": "effort/expense",
    "Tor": "goal/gate",
    "Innenstadt": "city center/downtown",
    "Kursus": "course",
    "Fahrrad": "bicycle",
    "Grüner": "Green (party member)",
    "Rathaus": "town hall/city hall",
    "Zuschauer": "spectator/viewer",
    "Beschwerde": "complaint",
    "Auszeichnung": "award/distinction",
    "Bestimmung": "regulation/purpose/determination",
    "Training": "training",
    "Übung": "exercise/practice",
    "Kritik": "criticism/critique",
    "Begegnung": "encounter/meeting",
    "Kampf": "fight/battle/struggle",
    "Beschluss": "decision/resolution",
    "Falle": "trap",
    "Versuch": "attempt/experiment",
    "Steuer": "tax",
    "Post": "mail/post office",
    "Morgen": "morning",
    "Besonderheit": "special feature/peculiarity",
    "Herstellung": "manufacture/production",
    "Betrag": "amount",
    "Spur": "trace/track/lane",
    "Norden": "north",
    "Neubau": "new building",
    "Wechsel": "change/exchange",
    "Verordnung": "regulation/ordinance",
    "Bestand": "stock/inventory",
    "Wachstum": "growth",
    "Bundestag": "Bundestag",
    "Formular": "form",
    "Geschenk": "gift/present",
    "Note": "grade/mark/note",
    "Dokumentation": "documentation",
    "Entwurf": "draft/design",
    "Vorfeld": "run-up/lead-up",
    "Auswertung": "evaluation/analysis",
    "Fach": "subject/compartment",
    "Nutzen": "benefit/use",
    "Fakultät": "faculty",
    "Ordnung": "order",
    "Erweiterung": "expansion/extension",
    "Getränk": "drink/beverage",
    "Informatik": "computer science",
    "Englisch": "English",
    "Figur": "figure",
    "Geschmack": "taste",
    "Nachteil": "disadvantage",
    "Abschnitt": "section/passage",
    "Einkauf": "purchase/shopping",
    "Hauptstadt": "capital city",
    "Sendung": "broadcast/delivery/shipment",
    "Begleitung": "accompaniment/escort",
    "Auseinandersetzung": "dispute/conflict",
    "Eingriff": "intervention/procedure",
    "Lehrerin": "female teacher",
    "Tonne": "ton/barrel/bin",
    "Bearbeitung": "processing/editing",
    "Frist": "deadline/period",
    "Aufmerksamkeit": "attention",
    "Einheit": "unit/unity",
    "Rede": "speech",
    "Brücke": "bridge",
    "Kleidung": "clothing/clothes",
    "Bahnhof": "train station",
    "Aktie": "share/stock",
    "Rezept": "recipe/prescription",
    "Stufe": "step/level/stage",
    "Fraktion": "parliamentary group/faction",
    "Gemüse": "vegetables",
    "Ausschuss": "committee",
    "Beschäftigung": "employment/occupation",
    "Erwartung": "expectation",
    "Genehmigung": "permission/approval/permit",
    "Länge": "length",
    "Laden": "shop/store",
    "Zuhause": "home",
    "Berg": "mountain/hill",
    "Rad": "wheel/bicycle",
    "Verletzung": "injury",
    "Stern": "star",
    "Bein": "leg",
    "Schmerz": "pain",
    "Stellungnahme": "statement/opinion",
    "Pause": "break/pause",
    "Zustimmung": "approval/consent",
    "Anleitung": "instructions/guide",
    "Einnahme": "income/intake",
    "Freizeit": "free time/leisure",
    "Motiv": "motive/motif",
    "Erhalt": "receipt/preservation",
    "Botschaft": "embassy/message",
    "Einschränkung": "restriction/limitation",
    "Sehensw\u00fcrdigkeit": "sight/attraction",
    "Eintritt": "entry/admission",
    "Berechnung": "calculation",
    "Handwerk": "craft/trade",
    "Unterkunft": "accommodation",
    "Kanal": "canal/channel",
    "Zulassung": "admission/permit/license",
    "Ansicht": "view/opinion",
    "Auftritt": "appearance/performance",
    "Stärkung": "strengthening",
    "Laufzeit": "term/duration/runtime",
    "Berater": "adviser/consultant",
    "Grundsatz": "principle",
    "Kündigung": "termination/cancellation",
    "Magazin": "magazine/warehouse",
    "Stein": "stone/rock",
    "Oberfläche": "surface",
    "Wanderung": "hike/migration",
    "Datenbank": "database",
    "Höhepunkt": "highlight/climax",
    "Mangel": "lack/shortage",
    "Stimmung": "mood/atmosphere",
    "Bruder": "brother",
    "Spitze": "top/tip/peak",
    "Dame": "lady",
    "Schwierigkeit": "difficulty",
    "Charakter": "character",
    "Rechner": "computer/calculator",
    "Großteil": "majority/large part",
    "Rest": "rest/remainder",
    "Macht": "power",
    "Rechtsanwalt": "lawyer/attorney",
    "Ermittlung": "investigation",
    "Abenteuer": "adventure",
    # Some very wrong ones I noticed in rank 500-1000
    "Wetter": "weather",
    "Drittel": "third",
    "Strecke": "route/distance/stretch",
    "Absatz": "paragraph/heel/sales",
    "Bahn": "train/railway/track",
    "Nachfrage": "demand/inquiry",
    "Lehrerin": "female teacher",
    "Einkauf": "purchase/shopping",
    "Beschwerde": "complaint",
    "Falle": "trap",
    "Grundstück": "plot/property",
    "Schreiben": "letter/writing",
    "Stärke": "strength/starch",
    "Stern": "star",
    "Bein": "leg",
    "Arbeitnehmer": "employee",
    "Straße": "street/road",
    "Nutzen": "benefit/use",
    "Kursus": "course",
    "Drittel": "third",
    "Vorjahr": "previous year",
    "Vorstand": "board of directors",
    "Ruhe": "peace/quiet/calm",
    "Holz": "wood",
    "Stoff": "material/fabric/substance",
    "Anliegen": "concern/request",
    "Verkehr": "traffic/transport",
    "Wand": "wall",
    "Tochter": "daughter",
    "Zug": "train/move/trait",
    "Lust": "desire/pleasure",
    "Gegensatz": "contrast/opposite",
    "Aufenthalt": "stay",
    "Belastung": "burden/strain",
    "Umsatz": "revenue/turnover",
    "Tor": "goal/gate",
    "Rathaus": "town hall/city hall",
    "Begegnung": "encounter/meeting",
    "Gelände": "terrain/grounds",
    "Quelle": "source/spring",
    "Parkplatz": "parking lot/car park",
    "Steuer": "tax",
    "Besonderheit": "special feature",
    "Format": "format",
    "Herstellung": "production/manufacture",
    "Betrag": "amount",
    "Lebensraum": "habitat/living space",
    "Spur": "trace/track/lane",
    "Wechsel": "change",
    "Bestand": "stock/inventory",
    "Bundestag": "Bundestag",
    "Note": "grade/mark",
    "Entwurf": "draft/design",
    "Fach": "subject/compartment",
    "Nutzen": "benefit/use",
    "Geschmack": "taste",
    "Nachteil": "disadvantage",
    "Abschnitt": "section",
    "Hauptstadt": "capital city",
    "Sendung": "broadcast/shipment",
    "Lehrerin": "female teacher",
    "Tonne": "ton/bin",
    "Frist": "deadline/period",
    "Einheit": "unit/unity",
    "Rede": "speech",
    "Brücke": "bridge",
    "Bahnhof": "train station",
    "Stufe": "step/level",
    "Laden": "shop/store",
    "Berg": "mountain",
    "Rad": "wheel/bicycle",
    "Stern": "star",
    "Bein": "leg",
    "Pause": "break/pause",
    "Freizeit": "free time/leisure",
    "Motiv": "motive/motif",
    "Botschaft": "embassy/message",
    "Eintritt": "entry/admission",
    "Handwerk": "craft/trade",
    "Unterkunft": "accommodation",
    "Kanal": "canal/channel",
    "Ansicht": "view/opinion",
    "Auftritt": "appearance/performance",
    "Laufzeit": "duration/runtime",
    "Grundsatz": "principle",
    "Stein": "stone/rock",
    "Oberfläche": "surface",
    "Höhepunkt": "highlight/climax",
    "Mangel": "lack/shortage",
    "Spitze": "top/tip/peak",
    "Rest": "rest/remainder",
    "Macht": "power",
    "Abenteuer": "adventure",
    "Verletzung": "injury",
    "Vorschrift": "regulation/rule",
    "Vergn\u00fcgen": "pleasure",
    # Additional 500-1000 corrections
    "Schneider": "tailor",
    "Schlot": "chimney/smokestack",
}

# ============================================================
# ADJECTIVE CORRECTIONS: { "word": "corrected english" }
# ============================================================
ADJECTIVE_CORRECTIONS = {
    "gut": "good",
    "groß": "big/large/tall",
    "eigen": "own",
    "klein": "small/little",
    "gemeinsam": "common/shared/joint",
    "verschieden": "different/various",
    "aktuell": "current",
    "wichtig": "important",
    "hoch": "high/tall",
    "schnell": "fast/quick",
    "möglich": "possible",
    "zusätzlich": "additional",
    "richtig": "correct/right",
    "genau": "exact/precise",
    "entsprechend": "corresponding/accordingly",
    "kurz": "short/brief",
    "unterschiedlich": "different/varying",
    "ganz": "whole/entire/quite",
    "stark": "strong",
    "persönlich": "personal",
    "zahlreich": "numerous",
    "einzeln": "individual/single",
    "deutlich": "clear/distinct",
    "bestimmt": "certain/specific",
    "frei": "free",
    "einfach": "simple/easy",
    "häufig": "frequent/common",
    "individuell": "individual",
    "schön": "beautiful/nice",
    "später": "later",
    "regelmäßig": "regular",
    "leicht": "light/easy",
    "sicher": "safe/certain/sure",
    "gesamt": "total/entire",
    "wirklich": "real/really",
    "jeweilig": "respective",
    "modern": "modern",
    "zentral": "central",
    "bekannt": "well-known/famous",
    "vergangen": "past/last",
    "gleichzeitig": "simultaneous",
    "weit": "far/wide",
    "weltweit": "worldwide/global",
    "kostenlos": "free (of charge)",
    "schwer": "heavy/difficult",
    "allgemein": "general",
    "passend": "suitable/fitting",
    "gesetzlich": "legal/statutory",
    "klar": "clear",
    "grundsätzlich": "fundamental/in principle",
    "tatsächlich": "actual/actually",
    "praktisch": "practical",
    "voll": "full",
    "gleich": "equal/same",
    "folgend": "following",
    "jährlich": "annual/yearly",
    "historisch": "historic/historical",
    "toll": "great/awesome",
    "künftig": "future/upcoming",
    "zust\u00e4ndig": "responsible",
    "beruflich": "professional/occupational",
    "wesentlich": "essential/significant",
    "spannend": "exciting",
    "vielfältig": "diverse/varied",
    "günstig": "cheap/favorable",
    "kommend": "coming/upcoming",
    "klassisch": "classic/classical",
    "vorhanden": "available/existing",
    "eng": "narrow/close/tight",
    "ehemalig": "former",
    "optimal": "optimal",
    "selten": "rare/rarely",
    "ähnlich": "similar",
    "umfassend": "comprehensive",
    "echt": "genuine/real",
    "unabhängig": "independent",
    "automatisch": "automatic",
    "fest": "firm/fixed/solid",
    "breit": "broad/wide",
    "wirtschaftlich": "economic",
    "erneut": "again/renewed",
    "gering": "low/small/slight",
    "einzig": "only/sole",
    "medizinisch": "medical",
    "geeignet": "suitable/appropriate",
    "vollständig": "complete",
    "zukünftig": "future",
    "intensiv": "intensive/intense",
    "ausreichend": "sufficient",
    "staatlich": "state/government",
    "heutig": "today's/current",
    "umfangreich": "extensive",
    "schlecht": "bad",
    "gesund": "healthy",
    "gesellschaftlich": "social/societal",
    "offiziell": "official",
    "herzlich": "warm/cordial",
    "maximal": "maximum",
    "rechtlich": "legal",
    "professionell": "professional",
    "bisherig": "previous/so far",
    "entscheidend": "decisive/crucial",
    "unmittelbar": "direct/immediate",
    "erheblich": "considerable/significant",
    "völlig": "complete/completely",
    "sinnvoll": "sensible/meaningful",
    "gezielt": "targeted",
    "hochwertig": "high-quality",
    "kommunal": "municipal/local",
    "tätig": "active/employed",
    "ehrenamtlich": "voluntary",
    "sächsisch": "Saxon",
    "natürlich": "natural/of course",
    "rund": "round/approximately",
    "betroffen": "affected/concerned",
    "flexibel": "flexible",
    "bequem": "comfortable/convenient",
    "fachlich": "professional/specialist",
    "falsch": "wrong/false",
    "dauerhaft": "permanent/lasting",
    "laufend": "ongoing/current",
    "weiß": "white",
    "freiwillig": "voluntary",
    "rein": "pure/clean",
    "teuer": "expensive",
    "einzigartig": "unique",
    "entfernt": "distant/remote",
    "ausführlich": "detailed",
    "bunt": "colorful",
    "evangelisch": "Protestant",
    "durchschnittlich": "average",
    "selbstverständlich": "obvious/natural",
    "tief": "deep",
    "kritisch": "critical",
    "hervorragend": "excellent/outstanding",
    "ursprünglich": "original/originally",
    "gewünscht": "desired/wanted",
    "divers": "diverse/various",
    "bewusst": "conscious/aware",
    "katholisch": "Catholic",
    "menschlich": "human/humane",
    "langsam": "slow",
    "kostenfrei": "free of charge",
    "inhaltlich": "in terms of content",
    "künstlich": "artificial",
    "mittel": "medium/middle",
    "körperlich": "physical/bodily",
    "französisch": "French",
    "grundlegend": "fundamental/basic",
    "langjährig": "long-standing",
    "elektrisch": "electric/electrical",
    "überwiegend": "predominantly/mainly",
    "angemessen": "appropriate/adequate",
    "eventuell": "possibly/perhaps",
    "selbstständig": "independent/self-employed",
    "sportlich": "athletic/sporty",
    "enorm": "enormous",
    "örtlich": "local",
    "einmalig": "unique/one-time",
    "eindeutig": "clear/unambiguous",
    "städtisch": "urban/municipal",
    "dringend": "urgent",
    "freundlich": "friendly",
    "sonstig": "other",
    "fertig": "finished/done/ready",
    "ruhig": "quiet/calm",
    "ausdrücklich": "explicit/express",
    "englisch": "English",
    "angenehm": "pleasant",
    "heiß": "hot",
    "ausländisch": "foreign",
    "erfahren": "experienced",
    "zuverlässig": "reliable",
    "rechtzeitig": "on time/timely",
    "wahrscheinlich": "probable/probably",
    "steigend": "rising/increasing",
    "gefährlich": "dangerous",
    "hart": "hard/tough",
    "riesig": "huge/enormous",
    "kalt": "cold",
    "strategisch": "strategic",
    "optisch": "visual/optical",
    "zeitlich": "temporal/time-related",
    "engagiert": "committed/dedicated",
    "gerecht": "fair/just",
    "frühzeitig": "early",
    "gegenseitig": "mutual",
    "intelligent": "intelligent",
    "zufrieden": "satisfied/content",
    "ärztlich": "medical",
    "offenbar": "apparent/obviously",
    "blau": "blue",
    "eigenständig": "independent",
    "schulisch": "school-related",
    "voraussichtlich": "expected/anticipated",
    "lecker": "delicious/tasty",
    "zugänglich": "accessible",
    "sauber": "clean",
    "berühmt": "famous",
    "qualifiziert": "qualified",
    "anerkannt": "recognized/approved",
    "kurzfristig": "short-term/short-notice",
    "heimisch": "native/local",
    "stabil": "stable",
    "vorliegend": "present/at hand",
    "hilfreich": "helpful",
    "mehrfach": "multiple/repeated",
    "lebendig": "alive/lively",
    "systematisch": "systematic",
    "außergewöhnlich": "exceptional/extraordinary",
    "ordentlich": "tidy/proper",
    "verbunden": "connected/linked",
    "nahe": "near/close",
    "wunderbar": "wonderful",
    "knapp": "scarce/tight/barely",
    "wunderschön": "beautiful/gorgeous",
    "fein": "fine/delicate",
    "konsequent": "consistent",
    "massiv": "massive/severe",
    "aufmerksam": "attentive",
    "fremd": "foreign/strange",
    "haupts\u00e4chlich": "mainly/primarily",
    "beteiligt": "involved/participating",
    "dunkel": "dark",
    "problemlos": "problem-free/smooth",
    "begeistert": "enthusiastic",
    "erhältlich": "available",
    "weitgehend": "largely/extensive",
    "detailliert": "detailed",
    "spät": "late",
    "stolz": "proud",
    "nett": "nice",
    "biologisch": "biological/organic",
    "chinesisch": "Chinese",
    "lieb": "dear/nice",
    "weiblich": "female/feminine",
    "heilig": "holy/sacred",
    "verbindlich": "binding/obligatory",
    "streng": "strict/severe",
    "kirchlich": "church/ecclesiastical",
    "glücklich": "happy/lucky",
    "stellvertretend": "deputy/acting",
    "damalig": "at that time/former",
    "anspruchsvoll": "demanding/ambitious",
    "landwirtschaftlich": "agricultural",
    "real": "real",
    "verständlich": "understandable",
    "vielseitig": "versatile/diverse",
    "chemisch": "chemical",
    "benötigt": "needed/required",
    "interkulturell": "intercultural",
    "kräftig": "strong/powerful",
    "ganzheitlich": "holistic",
    "organisatorisch": "organizational",
    "südlich": "southern",
    "gemeinnützig": "charitable/non-profit",
    "gewerblich": "commercial/industrial",
    "momentan": "current/at the moment",
    "potenziell": "potential",
    "reich": "rich/wealthy",
    "endgültig": "final/definitive",
    "herrlich": "wonderful/magnificent",
    "geistig": "mental/intellectual",
    "großzügig": "generous/spacious",
    "herk\u00f6mmlich": "conventional/traditional",
    "dick": "thick/fat",
    "wild": "wild",
    "emotional": "emotional",
    "ökonomisch": "economic",
    "juristisch": "legal/juridical",
    "sorgfältig": "careful/thorough",
    "angeblich": "alleged/supposedly",
    "liegend": "lying/horizontal",
    "renommiert": "renowned",
    "männlich": "male/masculine",
    "operativ": "operational/surgical",
    "offensichtlich": "obvious/evident",
    "gängig": "common/standard",
    "gelegen": "situated/convenient",
    "klinisch": "clinical",
    "krank": "ill/sick",
    "geschlossen": "closed",
    "total": "total/complete",
    "unglaublich": "incredible/unbelievable",
    "ungew\u00f6hnlich": "unusual",
    "ausgezeichnet": "excellent",
    "erreichbar": "reachable/accessible",
    "derartig": "such",
    "überraschend": "surprising",
    "alltäglich": "everyday/commonplace",
    "vertraut": "familiar",
    "spielerisch": "playful",
    "ungefähr": "approximately/about",
    "unzählig": "countless",
    "dicht": "dense/close/tight",
    "gewohnt": "usual/accustomed",
    "sprachlich": "linguistic",
    "lebend": "living/alive",
    "schlicht": "plain/simple",
    "begrenzt": "limited",
    "gegenwärtig": "current/present",
    "exakt": "exact/precise",
    "analog": "analog/analogous",
    "derzeitig": "current/present",
    "verlässlich": "reliable",
    "deutschlandweit": "Germany-wide",
    "abgeschlossen": "completed/closed",
    # Fix obviously wrong ones
    "bisexuell": "bisexual",
}

# ============================================================
# DUAL-GENDER NOUN CORRECTIONS
# Format: { "word": { "article": "corrected english", ... } }
# Only entries that need changing.
# ============================================================
DUAL_GENDER_CORRECTIONS = {
    "Mensch": {
        "der": "person/human being",
        "das": "wretch (derogatory, archaic)",
    },
    "Tag": {
        "der": "day",
        "das": "tag (markup)",
    },
    "Teil": {
        "der": "part/portion",
        "das": "piece/component",
    },
    "Kunde": {
        "die": "news/tidings (literary)",
        "der": "customer/client",
    },
    "Ort": {
        "der": "place/location",
        "das": "pointed tool/awl (archaic)",
    },
    "Fall": {
        "der": "case/fall",
        "das": "halyard (nautical)",
    },
    "Alter": {
        "der": "old man (colloquial)",
        "das": "age",
    },
    "Bund": {
        "der": "federation/alliance",
        "das": "bunch/bundle",
    },
    "Band": {
        "die": "band (music group)",
        "der": "volume (book)",
        "das": "ribbon/tape",
    },
    "Leiter": {
        "die": "ladder",
        "der": "leader/director",
    },
    "Maß": {
        "die": "liter of beer (Bavarian)",
        "das": "measure/degree",
    },
    "Gang": {
        "die": "gang",
        "der": "corridor/aisle/gear",
    },
    "Kaffee": {
        "der": "coffee",
        "das": "café (regional)",
    },
    "Steuer": {
        "die": "tax",
        "das": "steering wheel/helm",
    },
    "Lachs": {
        "der": "salmon",
        "das": "salmon (color)",
    },
    "Hummel": {
        "die": "bumblebee",
        "der": "breeding bull (dialectal)",
    },
    "Quark": {
        "der": "quark (curd cheese)",
        "das": "quark (physics)",
    },
    "Hefe": {
        "die": "yeast",
        "das": "wheat beer (colloquial)",
    },
    "Finne": {
        "die": "fin/blade",
        "der": "Finn",
    },
    "Stift": {
        "die": "?",
        "der": "pen/pencil",
        "das": "collegiate church/monastery",
    },
    "Vorsatz": {
        "der": "intention/resolution",
        "das": "endpaper (bookbinding)",
    },
    "Zimt": {
        "der": "cinnamon",
        "das": "cinnamon",
    },
    "Mahd": {
        "die": "mowing",
        "das": "alpine meadow",
    },
    "Alpaka": {
        "die": "alpaca wool",
        "der": "alpaca (animal)",
        "das": "nickel silver",
    },
    "Müsli": {
        "die": "?",
        "der": "?",
        "das": "muesli/granola",
    },
    "Gemahl": {
        "der": "husband (formal)",
        "das": "spouse (archaic)",
    },
    "Laube": {
        "die": "arbor/bower",
        "der": "bleak (fish)",
    },
    "Pole": {
        "die": "pole position",
        "der": "Pole (Polish person)",
    },
    "Transit": {
        "der": "transit",
        "das": "transit",
    },
    "Ex": {
        "die": "pop quiz (Bavarian)",
        "der": "ex (former partner)",
    },
    "Schote": {
        "die": "pod (botany)",
        "der": "fool (Northern German)",
    },
    "As": {
        "der": "ace",
        "das": "A-flat (music)",
    },
    "Mark": {
        "die": "mark (currency)",
        "das": "marrow/pith",
    },
    "Plastik": {
        "die": "sculpture",
        "der": "plastic",
    },
    "Funke": {
        "die": "radio equipment",
        "der": "spark",
    },
}


def fix_nouns(filepath):
    with open(filepath, encoding='utf-8') as f:
        data = json.load(f)

    changed = 0
    for noun in data['nouns']:
        word = noun['word']
        if word in NOUN_CORRECTIONS:
            old = noun['english']
            new = NOUN_CORRECTIONS[word]
            if old != new:
                noun['english'] = new
                changed += 1
                print(f"  NOUN: {word}: '{old}' -> '{new}'")

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\nFixed {changed} noun meanings.")
    return changed


def fix_adjectives(filepath):
    with open(filepath, encoding='utf-8') as f:
        data = json.load(f)

    changed = 0
    for adj in data['adjectives']:
        word = adj['word']
        if word in ADJECTIVE_CORRECTIONS:
            old = adj['english']
            new = ADJECTIVE_CORRECTIONS[word]
            if old != new:
                adj['english'] = new
                changed += 1
                print(f"  ADJ: {word}: '{old}' -> '{new}'")

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\nFixed {changed} adjective meanings.")
    return changed


def fix_dual_gender(filepath):
    with open(filepath, encoding='utf-8') as f:
        data = json.load(f)

    changed = 0
    for noun in data['nouns']:
        word = noun['word']
        if word in DUAL_GENDER_CORRECTIONS:
            corrections = DUAL_GENDER_CORRECTIONS[word]
            for gender_entry in noun['genders']:
                article = gender_entry['article']
                if article in corrections:
                    old = gender_entry['english']
                    new = corrections[article]
                    if old != new:
                        gender_entry['english'] = new
                        changed += 1
                        print(f"  DUAL: {article} {word}: '{old}' -> '{new}'")

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\nFixed {changed} dual-gender noun meanings.")
    return changed


if __name__ == '__main__':
    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    print("=== Fixing noun meanings ===")
    fix_nouns(os.path.join(base, 'data', 'nouns.json'))

    print("\n=== Fixing adjective meanings ===")
    fix_adjectives(os.path.join(base, 'data', 'adjectives.json'))

    print("\n=== Fixing dual-gender noun meanings ===")
    fix_dual_gender(os.path.join(base, 'data', 'dual-gender-nouns.json'))

    print("\nDone!")
