#!/usr/bin/env python3
"""Additional noun corrections for rank 1000-2000 and missed earlier ones."""
import json

EXTRA = {
    # Missed from top 500
    'Wirtschaft': 'economy/business',
    'Anspruch': 'claim/entitlement',
    'Förderung': 'support/funding/promotion',
    'Voraussetzung': 'prerequisite/requirement',
    'Recht': 'right/law',
    'Antrag': 'application/request',
    'Vorteil': 'advantage',
    'Sicherheit': 'safety/security',
    'Auto': 'car',
    'Vergleich': 'comparison',
    'Verfahren': 'procedure/process',
    'Besuch': 'visit',
    'Angabe': 'information/detail',
    'Beratung': 'advice/counseling',
    'Umsetzung': 'implementation',
    'Wort': 'word',
    'Technik': 'technology/technique',
    'Firma': 'company/firm',
    'Wahl': 'election/choice',
    'Wohnung': 'apartment/flat',
    'Auswahl': 'selection/choice',
    # Rank 1000-2000
    'Bezeichnung': 'name/designation',
    'Schwangerschaft': 'pregnancy',
    'Angriff': 'attack',
    'Auflage': 'edition/condition',
    'Fleisch': 'meat',
    'Abstimmung': 'vote/coordination',
    'Kredit': 'loan/credit',
    'Tat': 'act/deed',
    'Verpflichtung': 'obligation/commitment',
    'Konzern': 'corporation/group',
    'Ei': 'egg',
    'Westen': 'west',
    'Haltung': 'attitude/posture',
    'Sanierung': 'renovation/redevelopment',
    'Helfer': 'helper/assistant',
    'Geschwindigkeit': 'speed',
    'Arbeitszeit': 'working hours',
    'Kino': 'cinema/movie theater',
    'Ecke': 'corner',
    'Gegner': 'opponent/adversary',
    'Jubiläum': 'anniversary',
    'Geist': 'spirit/mind/ghost',
    'Apotheke': 'pharmacy',
    'Fußball': 'football/soccer',
    'Miete': 'rent',
    'Wind': 'wind',
    'Konkurrenz': 'competition',
    'Störung': 'disturbance/disruption',
    'Wärme': 'warmth/heat',
    'Vermittlung': 'mediation/placement',
    'Naturschutz': 'nature conservation',
    'Himmel': 'sky/heaven',
    'Übergang': 'transition',
    'Abgeordneter': 'member of parliament',
    'Versand': 'shipping/dispatch',
    'Jude': 'Jew',
    'Landtag': 'state parliament',
    'Einschätzung': 'assessment/estimate',
    'Schwester': 'sister/nurse',
    'Journalist': 'journalist',
    'Aussicht': 'view/prospect',
    'Schlüssel': 'key',
    'Chemie': 'chemistry',
    'Freundin': 'friend/girlfriend',
    'Eingang': 'entrance',
    'Star': 'star (celebrity)/starling',
    'Begründung': 'justification/reasoning',
    'Verantwortlicher': 'person in charge',
    'Wein': 'wine',
    'Herkunft': 'origin',
    'Schulung': 'training',
    'Sicherung': 'fuse/safeguard',
    'Tasche': 'bag/pocket',
    'Belang': 'concern/interest',
    'Tabelle': 'table/chart',
    'Fisch': 'fish',
    'Schnitt': 'cut/average',
    'Zuschuss': 'grant/subsidy',
    'Baustein': 'building block/component',
    'Gremium': 'committee/board',
    'Übernahme': 'takeover/acquisition',
    'Befragter': 'respondent/interviewee',
    'Einwilligung': 'consent',
    'Benutzer': 'user',
    'Interessent': 'prospective customer',
    'Gang': 'corridor/aisle/gear',
    'Kasse': 'cash register/checkout',
    'Optimierung': 'optimization',
    'Vorbild': 'role model',
    'Feature': 'feature',
    'Talent': 'talent',
    'Transport': 'transport',
    'Mut': 'courage',
    'Weihnachten': 'Christmas',
    'Krankenversicherung': 'health insurance',
    'Oberbürgermeister': 'mayor',
    'Zelle': 'cell',
    'Anstieg': 'increase/rise',
    'Katze': 'cat',
    'Verhandlung': 'negotiation/trial',
    'Vogel': 'bird',
    'Vorgang': 'process/procedure',
    'Erhebung': 'survey/elevation',
    'Fest': 'celebration/festival',
    'Gewässer': 'body of water',
    'Fluss': 'river/flow',
    'Merkmal': 'feature/characteristic',
    'Gebrauch': 'use/usage',
    'Ohr': 'ear',
    'Vertrieb': 'sales/distribution',
    'Betriebssystem': 'operating system',
    'Fonds': 'fund',
    'Mischung': 'mixture/mix',
    'Endgerät': 'end device/terminal',
    'Volk': 'people/nation',
    'Zentimeter': 'centimeter',
    'Durchschnitt': 'average',
    'Einhaltung': 'compliance/adherence',
    'Empfänger': 'recipient/receiver',
    'Kloster': 'monastery/convent',
    'Angelegenheit': 'matter/affair',
    'Brand': 'fire/blaze',
    'Labor': 'laboratory/lab',
    'Burg': 'castle/fortress',
    'Muster': 'pattern/sample',
    'Pferd': 'horse',
    'Architekt': 'architect',
    'Minister': 'minister',
    'Umzug': 'move/parade',
    'Zeugnis': 'certificate/report card',
    'Hafen': 'harbor/port',
    'Verbreitung': 'spread/distribution',
    'Geschlecht': 'gender/sex',
    'Rücken': 'back',
    'Auflösung': 'resolution/dissolution',
    'Rohstoff': 'raw material',
    'Sparkasse': 'savings bank',
    'Akku': 'rechargeable battery',
    'Autorin': 'female author',
    'Klage': 'complaint/lawsuit',
    'Not': 'need/distress/emergency',
    'Gegenwart': 'present/presence',
    'Klinikum': 'hospital',
    'Spannung': 'tension/voltage/suspense',
    'Erziehung': 'upbringing/education',
    'Exemplar': 'copy/specimen',
    'Gutachten': 'expert report',
    'Meister': 'master/champion',
    'Recherche': 'research/investigation',
    'Entfernung': 'distance/removal',
    'Last': 'load/burden',
    'Masse': 'mass/crowd',
    'Stellung': 'position',
    'Rand': 'edge/margin',
    'Ausblick': 'outlook/view',
    'Bezirk': 'district',
    'Unterhaltung': 'conversation/entertainment',
    'Wagen': 'car/wagon',
    'Direktor': 'director',
    'Erfüllung': 'fulfillment',
    'Ergänzung': 'addition/supplement',
    'Gut': 'estate/good',
    'Symbol': 'symbol',
    'Speise': 'dish/food',
    'Steuerung': 'control',
    'Dozent': 'lecturer',
    'Finanzamt': 'tax office',
    'Boot': 'boat',
    'Eis': 'ice/ice cream',
    'Buchung': 'booking',
    'Insekt': 'insect',
    'Lager': 'warehouse/camp/bearing',
    'Trick': 'trick',
    'Erbe': 'inheritance/heritage',
    'Gesundheitswesen': 'healthcare system',
    'Abfall': 'waste/garbage',
    'Beweis': 'proof/evidence',
    'Kulisse': 'backdrop/scenery',
    'Frucht': 'fruit',
    'Gehirn': 'brain',
    'Kuchen': 'cake',
    'Notwendigkeit': 'necessity',
    'Besitz': 'possession/property',
    'Sorte': 'type/sort',
    'Speicher': 'storage/memory/attic',
    'Kern': 'core/kernel',
    'Probe': 'rehearsal/sample/test',
    'Verkäufer': 'seller/salesperson',
    'Abitur': 'school-leaving exam',
    'Anleger': 'investor/dock',
    'Redaktion': 'editorial office',
    'Rubrik': 'section/category',
    'Seele': 'soul',
    'Anwalt': 'lawyer',
    'Entstehung': 'origin/creation',
    'Flucht': 'escape/flight',
    'Großstadt': 'city/metropolis',
    'Zahn': 'tooth',
    'Zucker': 'sugar',
    'Antragsteller': 'applicant',
    'Aufklärung': 'enlightenment/clarification',
    'Cookie': 'cookie',
    'Filiale': 'branch',
    'Reichweite': 'range/reach',
    'Ausrichtung': 'alignment/orientation',
    'Handlung': 'action/plot',
    'Sender': 'broadcaster/transmitter',
    'Übertragung': 'transfer/transmission/broadcast',
    'Widerspruch': 'contradiction/objection',
    'Stadtverwaltung': 'city administration',
    'Streit': 'dispute/argument',
    'Stress': 'stress',
    'Bistum': 'diocese',
    'Kreuz': 'cross/back',
    'Reifen': 'tire/tyre',
    'Staffel': 'season/relay',
    'Zutat': 'ingredient',
    'Erhöhung': 'increase',
    'Gegend': 'area/region',
    'Kapazität': 'capacity',
    'Möbel': 'furniture',
    'Autobahn': 'highway/motorway',
    'Baustelle': 'construction site',
    'Fazit': 'conclusion',
    'Schiff': 'ship',
    'Steigerung': 'increase/improvement',
    'Verstoß': 'violation/breach',
    'Bewusstsein': 'awareness/consciousness',
    'Vermögen': 'assets/fortune/ability',
    'Mode': 'fashion',
    'Nase': 'nose',
    'Richter': 'judge',
    'Warenkorb': 'shopping cart',
    'Wurzel': 'root',
    'Erwerb': 'acquisition/purchase',
    'Flugzeug': 'airplane/aircraft',
    'Überwachung': 'monitoring/surveillance',
    'Wohnraum': 'living space/housing',
    'Armut': 'poverty',
    'Bier': 'beer',
    'Papst': 'pope',
    'Heft': 'notebook/booklet',
    'Onlineshop': 'online shop',
    'Zoll': 'customs/inch',
    'Mietwagen': 'rental car',
    'Schrift': 'writing/font/script',
    'Urkunde': 'certificate/document',
    'Brot': 'bread',
    'Vereinigung': 'association/unification',
    'Nahrung': 'food/nourishment',
    'Breite': 'width/breadth',
    'Sportler': 'athlete',
    'Beratungsstelle': 'advice center',
    'Jahrgang': 'year/vintage',
    'Hochzeit': 'wedding',
    'Hof': 'courtyard/farm/court',
    'Maßstab': 'scale/standard',
    'Vergütung': 'compensation/remuneration',
    'Verpackung': 'packaging',
    'Werkstatt': 'workshop/garage',
    'Auftraggeber': 'client/customer',
    'Bedienung': 'service/operation',
    'Fassung': 'version/composure/socket',
    'Klang': 'sound',
    'Preisträger': 'award winner',
    'Bauer': 'farmer',
    'Gas': 'gas',
    'Auftakt': 'start/prelude',
    'Trennung': 'separation',
    'Ehe': 'marriage',
    'Schicht': 'layer/shift',
    'Abhängigkeit': 'dependence/addiction',
    'Begeisterung': 'enthusiasm',
    'Müll': 'garbage/rubbish/trash',
    'Profi': 'professional',
    'Räumlichkeit': 'premises',
    'Rückkehr': 'return',
    'Tafel': 'board/blackboard',
    'Widerstand': 'resistance',
    'Ausgangspunkt': 'starting point',
    'Bandbreite': 'range/bandwidth',
    'Lauf': 'run/course',
    'Bauteil': 'component',
    'Milch': 'milk',
    'Spaziergang': 'walk/stroll',
    'Abbildung': 'illustration/figure',
    'Bescheid': 'notification/notice',
    'Landgericht': 'regional court',
    'Ärztin': 'female doctor',
    'Entspannung': 'relaxation',
    'Rechenzentrum': 'data center',
    'Hürde': 'hurdle',
    'Beeinträchtigung': 'impairment',
    'Rentenversicherung': 'pension insurance',
    'Stipendium': 'scholarship',
    'Verkehrsmittel': 'means of transport',
    'Vorsicht': 'caution',
    'Autofahrer': 'driver/motorist',
    'Button': 'button',
    'Genuss': 'enjoyment/pleasure',
    'Verfügbarkeit': 'availability',
    'Abgabe': 'submission/levy',
    'Aufruf': 'call/appeal',
    'Rang': 'rank',
    'Ruf': 'reputation/call',
    'Umbau': 'renovation/conversion',
    'Buchstabe': 'letter (of alphabet)',
    'Festplatte': 'hard drive',
    'Annahme': 'assumption/acceptance',
    'Hindernis': 'obstacle',
    'Tee': 'tea',
    'Umweltschutz': 'environmental protection',
    'Inhaber': 'owner/holder',
    'Kopie': 'copy',
    'Radfahrer': 'cyclist',
    'Betreuer': 'supervisor/caretaker',
    'Salz': 'salt',
    'Bereitschaft': 'readiness/willingness',
    'Erfassung': 'recording/registration',
    'Erlaubnis': 'permission',
    'Altersgruppe': 'age group',
    "Staatsanwaltschaft": "public prosecutor's office",
    'Arbeitsgemeinschaft': 'working group',
    'Blüte': 'blossom/bloom',
    'Schwäche': 'weakness',
    'Sportart': 'type of sport',
    'Betrachtung': 'consideration/observation',
    'Waffe': 'weapon',
    'Wahrscheinlichkeit': 'probability',
    'Griff': 'handle/grip',
    'Reisender': 'traveler',
    'Anhänger': 'follower/trailer/pendant',
    'Anruf': 'phone call',
    'Chor': 'choir/chorus',
    'Zuständigkeit': 'responsibility/jurisdiction',
    'Auffassung': 'view/understanding',
    'Party': 'party',
    'Übersetzung': 'translation',
    'Haftung': 'liability',
    'Rückgang': 'decline/decrease',
    'Schönheit': 'beauty',
    'Verbrauch': 'consumption',
    'Wohnzimmer': 'living room',
    'Hansestadt': 'Hanseatic city',
    'Naturwissenschaft': 'natural science',
    'Bilanz': 'balance sheet/outcome',
    'Reich': 'empire/kingdom',
    'Tumor': 'tumor',
    'Zeitalter': 'era/age',
    'Anschaffung': 'purchase/acquisition',
    'Bedenken': 'concern/doubt',
    'Bestätigung': 'confirmation',
    'Börse': 'stock exchange',
    'Rassismus': 'racism',
    'Zuwendung': 'attention/contribution',
    'Agenda': 'agenda',
    'Anlaufstelle': 'contact point',
    'Ausgleich': 'compensation/balance',
    'Benutzung': 'use',
    'Exkursion': 'excursion/field trip',
    'Radweg': 'bicycle path',
    'Tal': 'valley',
    'Unsicherheit': 'uncertainty/insecurity',
    'Verlängerung': 'extension',
    'Gewerkschaft': 'trade union',
    'Tempo': 'speed/pace',
    'Verbot': 'ban/prohibition',
    'Einzug': 'move-in/entry',
    'Naturschutzgebiet': 'nature reserve',
    'Schicksal': 'fate/destiny',
    'Welle': 'wave',
    'Hilfsmittel': 'aid/tool',
    'Kühlschrank': 'refrigerator/fridge',
    'Reinigung': 'cleaning/dry cleaner',
    'Balkon': 'balcony',
    'Motorrad': 'motorcycle',
    'Apotheker': 'pharmacist',
    'Schatten': 'shadow/shade',
    'Anbindung': 'connection/link',
    'Darlehen': 'loan',
    'Sachverhalt': 'facts/circumstances',
    'Sprung': 'jump/crack',
    'Unternehmung': 'enterprise',
    'Absicherung': 'safeguard/insurance',
    'Aufstieg': 'rise/ascent',
    'Held': 'hero',
    'Rundgang': 'tour',
    'Spiegel': 'mirror',
    'Handwerker': 'craftsman',
    'Ausflugsziel': 'excursion destination',
    'Wertschätzung': 'appreciation/esteem',
    'Hauptbahnhof': 'main train station',
    'Lieferant': 'supplier',
    'Polizist': 'police officer',
    'Wirksamkeit': 'effectiveness',
    'Bezahlung': 'payment',
    'Dom': 'cathedral',
    'Grundgesetz': 'Basic Law (constitution)',
    'Ratgeber': 'guide/adviser',
    'Stuhl': 'chair',
    'Abrechnung': 'billing/settlement',
    'Sand': 'sand',
    'Achtung': 'attention/respect',
    'Applikation': 'application',
    'Eigentum': 'property/ownership',
    'Errichtung': 'construction/establishment',
    'Nebenwirkung': 'side effect',
    'Regisseur': 'director (film)',
    'Berufung': 'appeal/vocation',
    'Ferienhaus': 'holiday home',
    'Flasche': 'bottle',
    'Gesetzentwurf': 'bill/draft law',
    'Gewerbe': 'trade/business',
    'Kapital': 'capital',
    'Lohn': 'wage/salary',
    'Mittelstand': 'small and medium businesses',
    'Turm': 'tower',
    'Halbjahr': 'half year',
    'Justiz': 'judiciary',
    'Lehrgang': 'course',
    'Realisierung': 'realization/implementation',
    'Verbraucherschutz': 'consumer protection',
    'Anschrift': 'address',
    'Bauherr': 'building owner',
    'Krebs': 'cancer/crab',
    'Ertrag': 'yield/revenue',
    'Saal': 'hall',
    'Schriftsteller': 'writer/author',
    'Abwechslung': 'variety/change',
    'Wettkampf': 'competition/contest',
    'Katalog': 'catalog',
    'Küste': 'coast',
    'Stadtrat': 'city council',
    'Toter': 'dead person',
    'Wähler': 'voter',
    'Flüssigkeit': 'liquid/fluid',
    'Kanzlei': 'law firm/office',
    'Keller': 'basement/cellar',
    'Protokoll': 'minutes/protocol',
    'Rückseite': 'back/reverse',
    'Schatz': 'treasure/darling',
    'Kleid': 'dress',
    'Ministerin': 'female minister',
    'Mühe': 'effort/trouble',
    'Rechtsprechung': 'jurisdiction',
    'Verzeichnis': 'directory/index',
    'Vorgehensweise': 'approach/procedure',
    'Frühling': 'spring',
    'Säule': 'column/pillar',
    'Vertretung': 'representation/deputy',
    'Anbau': 'extension/cultivation',
    'Ausmaß': 'extent/scale',
    'Feier': 'celebration/party',
    'Halt': 'stop/support',
    'Kochen': 'cooking',
    'Kürze': 'brevity',
    'Quote': 'rate/quota',
    'Überzeugung': 'conviction/belief',
    'Anordnung': 'order/arrangement',
    'Beachtung': 'attention/notice',
    'Bekannter': 'acquaintance',
    'Laune': 'mood',
    "Führerschein": "driver's license",
    'Mund': 'mouth',
    'Wohl': 'well-being/welfare',
    'Box': 'box/speaker',
    'Fertigung': 'production/manufacturing',
    'Bekämpfung': 'combating',
    'Decke': 'blanket/ceiling',
    'Apfel': 'apple',
    'Beauftragter': 'commissioner/representative',
    'Mitarbeit': 'collaboration',
    'Zusammensetzung': 'composition',
    'Beirat': 'advisory board',
    'Lizenz': 'license',
    'Brust': 'chest/breast',
    'Fachgebiet': 'field/specialty',
    'Kaiser': 'emperor',
    'Gehäuse': 'housing/case',
    'Moderator': 'host/presenter',
    'Ordner': 'folder/binder',
    'Pool': 'pool',
    'Abwicklung': 'handling/processing',
    'Ausbildungsplatz': 'training position',
    'Akte': 'file/record',
    'Französisch': 'French',
    'Übernachtung': 'overnight stay',
    # Fixes in top 500 still not covered
    'Rabatte': 'discount',
    'Berichterstattung': 'reporting',
    'Dusche': 'shower',
    'Logistik': 'logistics',
    'Marktplatz': 'marketplace',
    'Tierpark': 'zoo',
    'Elektromobilität': 'electromobility',
    'Schneider': 'tailor',
}

with open('data/nouns.json', encoding='utf-8') as f:
    data = json.load(f)

changed = 0
for noun in data['nouns']:
    word = noun['word']
    if word in EXTRA:
        old = noun['english']
        new = EXTRA[word]
        if old != new:
            noun['english'] = new
            changed += 1
            print(f"  {noun['rank']:4d} {word}: '{old}' -> '{new}'")

with open('data/nouns.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nFixed {changed} additional noun meanings.")
