#!/usr/bin/env python3
"""Fix remaining empty translations for the most important (lowest-rank) words."""
import json, sys
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

# Top-priority empty adjective translations (rank < 2000)
ADJ_FILLS = {
    'experimentell': 'experimental',
    'niedergelassen': 'established/settled (medical practice)',
    'hauseigen': 'in-house/own',
    'medial': 'media/medial',
    'gemacht': 'made/done',
    'geehrt': 'honored/dear',
    'erwartet': 'expected',
    'hochkarätig': 'top-class/high-caliber',
    'passgenau': 'precisely fitting/tailored',
    'unklar': 'unclear',
    'markant': 'striking/distinctive',
    'freiberuflich': 'freelance',
    'kooperativ': 'cooperative',
    'anderweitig': 'other/alternative',
    'angeschlossen': 'connected/affiliated',
    'verschärft': 'tightened/intensified',
    'generell': 'general',
    'hochschulisch': 'university/higher education',
    'resultierend': 'resulting',
    'gefordert': 'demanded/required',
    'angenehm': 'pleasant/comfortable',
    'zweckgebunden': 'earmarked/dedicated',
    'selbstverständlich': 'self-evident/obvious',
    'gleichberechtigt': 'equal/with equal rights',
    'ausgewogen': 'balanced',
    'innerstädtisch': 'inner-city',
    'kreativ': 'creative',
    'bemerkt': 'noticed/noted',
    'vorrangig': 'priority/primary',
    'ausstehend': 'outstanding/pending',
    'reformiert': 'reformed',
    'geboten': 'offered/advisable',
    'spannend': 'exciting/thrilling',
    'wohlwollend': 'benevolent',
    'nebenamtlich': 'part-time/secondary',
    'wohnortnah': 'close to home',
    'datenschutzkonform': 'data protection compliant',
    'herkunftssprachlich': 'heritage language',
    'interreligiös': 'interreligious',
    'niedrigschwellig': 'low-threshold/easily accessible',
    'partizipativ': 'participatory',
    'überkonfessionell': 'interdenominational',
    'ausgewählt': 'selected/chosen',
    'betreut': 'supervised/cared for',
    'strukturiert': 'structured',
    'qualifiziert': 'qualified',
    'renoviert': 'renovated',
    'abgeschlossen': 'completed/closed',
    'anerkannt': 'recognized',
    'geregelt': 'regulated',
    'gefördert': 'funded/promoted',
    'berechtigt': 'entitled/justified',
    'verpflichtet': 'obligated',
    'betroffen': 'affected',
    'bewährt': 'proven',
    'angewandt': 'applied',
    'ausgeprägt': 'pronounced/distinctive',
    'fortgeschritten': 'advanced',
    'eingebettet': 'embedded',
    'unterstellt': 'subordinate/alleged',
    'zugewiesen': 'assigned/allocated',
    'zugeordnet': 'assigned/associated',
    'eingestellt': 'hired/adjusted/discontinued',
    'eingetragen': 'registered',
    'enthalten': 'contained',
    'gestaltet': 'designed/shaped',
    'versichert': 'insured',
    'verankert': 'anchored/established',
    'verbunden': 'connected/associated',
    'beauftragt': 'commissioned',
    'befristet': 'temporary/fixed-term',
    'begründet': 'justified/founded',
    'benachteiligt': 'disadvantaged',
    'beschäftigt': 'employed/busy',
    'behindert': 'disabled',
    'interkulturell': 'intercultural',
    'innerbetrieblich': 'in-house/internal',
    'ordentlich': 'proper/tidy/regular',
    'zunehmend': 'increasing',
    'dauernd': 'lasting/permanent',
    'vergleichend': 'comparative',
    'vorwiegend': 'predominantly',
    'überwiegend': 'predominantly/mainly',
    'zutreffend': 'applicable/accurate',
    'maßgebend': 'authoritative/decisive',
    'abweichend': 'deviating/different',
    'angrenzend': 'adjacent/bordering',
    'bedeutend': 'significant/important',
    'begleitend': 'accompanying',
    'entscheidend': 'decisive/crucial',
    'entsprechend': 'corresponding/accordingly',
    'ergänzend': 'supplementary',
    'führend': 'leading',
    'laufend': 'current/ongoing',
    'übergeordnet': 'superior/overarching',
    'umfassend': 'comprehensive',
    'überragend': 'outstanding',
    'zugrunde': 'underlying',
    'zusammenfassend': 'summarizing',
    'ausschließend': 'exclusive/excluding',
    'tragend': 'load-bearing/supporting',
    'ansprechend': 'appealing/attractive',
    'aussagekräftig': 'meaningful/informative',
    'bahnbrechend': 'groundbreaking',
    'beruhigend': 'calming/reassuring',
    'einnehmend': 'charming/engaging',
    'ermutigend': 'encouraging',
    'faszinierend': 'fascinating',
    'gewinnend': 'winning/charming',
    'herausfordernd': 'challenging',
    'inspirierend': 'inspiring',
    'irritierend': 'irritating',
    'motivierend': 'motivating',
    'naheliegend': 'obvious/nearby',
    'überraschend': 'surprising',
    'überwältigend': 'overwhelming',
    'wegweisend': 'pioneering',
    'zufriedenstellend': 'satisfactory',
    'zusammenhängend': 'coherent/connected',
    'empfehlenswert': 'recommendable',
    'erwähnenswert': 'worth mentioning',
    'lebenswert': 'worth living',
    'sehenswert': 'worth seeing',
    'wissenswert': 'worth knowing',
    'liebenswert': 'lovable/endearing',
    'beachtenswert': 'noteworthy',
    'erstrebenswert': 'desirable',
    'nennenswert': 'noteworthy/significant',
    'preiswert': 'inexpensive/good value',
    'vertrauenswürdig': 'trustworthy',
    'glaubwürdig': 'credible',
    'strafwürdig': 'punishable',
    'preiswürdig': 'prize-worthy',
    'sehenswürdig': 'worth seeing',
}

# Top-priority empty noun translations
NOUN_FILLS = {
    'Abwägung': 'consideration/weighing',
    'Achtsamkeit': 'mindfulness',
    'Anerkennung': 'recognition/appreciation',
    'Anforderung': 'requirement/demand',
    'Anleitung': 'instruction/guide',
    'Anpassung': 'adaptation/adjustment',
    'Anregung': 'suggestion/stimulation',
    'Ansprechpartner': 'contact person',
    'Aufbereitung': 'preparation/processing',
    'Aufbewahrung': 'storage/safekeeping',
    'Aufklärung': 'education/enlightenment',
    'Aufwand': 'effort/expense',
    'Ausarbeitung': 'elaboration/drafting',
    'Ausbildungsplatz': 'training position',
    'Ausgangslage': 'starting situation',
    'Ausgestaltung': 'design/arrangement',
    'Ausgleich': 'compensation/balance',
    'Ausschreibung': 'tender/announcement',
    'Ausstattung': 'equipment/furnishing',
    'Beanstandung': 'complaint/objection',
    'Bearbeitung': 'processing/editing',
    'Bedürfnis': 'need/requirement',
    'Befragung': 'survey/interrogation',
    'Begegnung': 'encounter/meeting',
    'Begleitung': 'accompaniment',
    'Begutachtung': 'assessment/evaluation',
    'Behebung': 'rectification/repair',
    'Belehrung': 'instruction/admonition',
    'Bemühung': 'effort/endeavor',
    'Benachrichtigung': 'notification',
    'Benennung': 'designation/naming',
    'Bereitstellung': 'provision/deployment',
    'Berichterstattung': 'reporting/coverage',
    'Beschaffenheit': 'nature/condition',
    'Beschaffung': 'procurement',
    'Bescheinigung': 'certificate/confirmation',
    'Beschwerde': 'complaint/appeal',
    'Bestätigung': 'confirmation',
    'Betreuung': 'care/supervision',
    'Bevölkerung': 'population',
    'Dankbarkeit': 'gratitude',
    'Dringlichkeit': 'urgency',
    'Durchsetzung': 'enforcement',
    'Einbeziehung': 'inclusion/involvement',
    'Einhaltung': 'compliance/observance',
    'Einreichung': 'submission',
    'Einsicht': 'insight/inspection',
    'Einwand': 'objection',
    'Empfänger': 'recipient',
    'Entlastung': 'relief/discharge',
    'Entschädigung': 'compensation',
    'Erbschaft': 'inheritance',
    'Erfassung': 'recording/registration',
    'Erholung': 'recreation/recovery',
    'Erlass': 'decree/waiver',
    'Ermittlung': 'investigation',
    'Errichtung': 'construction/establishment',
    'Erschließung': 'development',
    'Fachbereich': 'department/field',
    'Fachkraft': 'skilled worker/specialist',
    'Fehlbetrag': 'shortfall/deficit',
    'Feststellung': 'determination/finding',
    'Fördermittel': 'funding/grants',
    'Förderprogramm': 'funding program',
    'Fortschreibung': 'updating',
    'Fragestellung': 'question/issue',
    'Freigabe': 'release/approval',
    'Freistellung': 'exemption/release',
    'Genehmigung': 'approval/permit',
    'Gesamtkosten': 'total costs',
    'Gesetzgebung': 'legislation',
    'Gewährleistung': 'warranty/guarantee',
    'Gleichbehandlung': 'equal treatment',
    'Gleichstellung': 'equality',
    'Gutachten': 'expert opinion/report',
    'Haftung': 'liability',
    'Handlungsbedarf': 'need for action',
    'Herausforderung': 'challenge',
    'Herkunft': 'origin',
    'Hinweis': 'note/reference/hint',
    'Inanspruchnahme': 'utilization/use',
    'Infrastruktur': 'infrastructure',
    'Instandhaltung': 'maintenance',
    'Kennzeichnung': 'labeling/marking',
    'Klarstellung': 'clarification',
    'Laufzeit': 'term/duration',
    'Lebensqualität': 'quality of life',
    'Leitfaden': 'guide/guideline',
    'Leitlinie': 'guideline',
    'Mitwirkung': 'participation',
    'Nachweis': 'proof/evidence',
    'Neubau': 'new building',
    'Rechtfertigung': 'justification',
    'Sachverhalt': 'facts/circumstances',
    'Schwerpunkt': 'focus/priority',
    'Sicherstellung': 'ensuring/securing',
    'Stellungnahme': 'statement/position',
    'Überprüfung': 'review/verification',
    'Umsetzung': 'implementation',
    'Unterkunft': 'accommodation/lodging',
    'Verbesserung': 'improvement',
    'Verbreitung': 'distribution/spread',
    'Vergütung': 'remuneration/compensation',
    'Vermittlung': 'mediation/placement',
    'Verpflichtung': 'obligation/commitment',
    'Versorgung': 'supply/care/provision',
    'Verteilung': 'distribution',
    'Verwaltung': 'administration',
    'Vollzug': 'enforcement/execution',
    'Voraussetzung': 'prerequisite',
    'Vorhaben': 'project/intention',
    'Wahrnehmung': 'perception',
    'Weiterbildung': 'continuing education',
    'Wertschätzung': 'appreciation',
    'Widerspruch': 'objection/contradiction',
    'Zielsetzung': 'objective/goal',
    'Zugehörigkeit': 'belonging/affiliation',
    'Zuständigkeit': 'jurisdiction/responsibility',
    'Zustimmung': 'approval/consent',
}

def main():
    # Fix adjectives
    with open('data/adjectives.json', 'r', encoding='utf-8') as f:
        adj_data = json.load(f)

    adj_fixed = 0
    for a in adj_data['adjectives']:
        if a['word'] in ADJ_FILLS and not (a.get('english') or '').strip():
            a['english'] = ADJ_FILLS[a['word']]
            adj_fixed += 1

    still_empty_adj = sum(1 for a in adj_data['adjectives'] if not (a.get('english') or '').strip())
    print(f'Adjectives: filled {adj_fixed} empty translations')
    print(f'Adjectives still empty: {still_empty_adj}')

    with open('data/adjectives.json', 'w', encoding='utf-8') as f:
        json.dump(adj_data, f, ensure_ascii=False, indent=2)

    # Fix nouns
    with open('data/nouns.json', 'r', encoding='utf-8') as f:
        noun_data = json.load(f)

    noun_fixed = 0
    for n in noun_data['nouns']:
        if n['word'] in NOUN_FILLS and not (n.get('english') or '').strip():
            n['english'] = NOUN_FILLS[n['word']]
            noun_fixed += 1

    still_empty_nouns = sum(1 for n in noun_data['nouns'] if not (n.get('english') or '').strip())
    print(f'\nNouns: filled {noun_fixed} empty translations')
    print(f'Nouns still empty: {still_empty_nouns}')

    with open('data/nouns.json', 'w', encoding='utf-8') as f:
        json.dump(noun_data, f, ensure_ascii=False, indent=2)

    print('\nDone!')

if __name__ == '__main__':
    main()
