"""Find CURRENT_SUPERSET entries where the first slash-separated sense is
suspicious (looks like MT garbage) but DeepL's pick is a later sense in the
slash list. Proposes reordering so the trustworthy sense leads.
"""
import json
import re
from pathlib import Path

DIFF = Path('audit/deepl_diff')
OUT = DIFF / 'proposed_reorderings.md'

# Words that signal a sense was generated by bad MT — should not lead a gloss
SUSPICIOUS_HEAD_TOKENS = {
    'baloney', 'barm', 'dregs', 'landspout', 'pantaloon', 'cellarer', 'cellarman',
    'cellarmaster', 'aiding', 'banger',  # "banger" for Schüssel was wrong
    'penchant',  # often wrong (Faible)
}
# These tokens are only suspicious when the German word looks like a compound
# (long; rough heuristic). Short German words like Abteil → compartment are fine.
COMPOUND_ONLY_SUSPICIOUS = {
    'compartment',
    'attachment',
}
COMPOUND_LEN_THRESHOLD = 11

# Phrases (multi-word) that as primary sense are suspicious
SUSPICIOUS_PHRASES = [
    'aiding and abetting',  # Beihilfe MT
    'driving force',  # Hefe
    'tall tale',  # Seemannsgarn — "yarn" better
]


def looks_suspicious(sense, german_word=''):
    s = sense.strip().lower()
    first = s.split()[0] if s else ''
    if first in SUSPICIOUS_HEAD_TOKENS:
        return True
    if first in COMPOUND_ONLY_SUSPICIOUS and len(german_word) >= COMPOUND_LEN_THRESHOLD:
        return True
    for phrase in SUSPICIOUS_PHRASES:
        if s.startswith(phrase):
            return True
    return False


def split_senses(s):
    return [p.strip() for p in re.split(r'\s*/\s*', s) if p.strip()]


def main():
    proposals = []
    rows = json.loads((DIFF / 'nouns_classified.json').read_text(encoding='utf-8'))

    for r in rows:
        if r['category'] != 'CURRENT_SUPERSET':
            continue
        senses = split_senses(r['current'])
        if len(senses) < 2:
            continue
        if not looks_suspicious(senses[0], r['word']):
            continue
        # The DeepL pick is in the slash list (by definition of CURRENT_SUPERSET).
        # Build reordered: DeepL pick first, then the rest, suspicious senses dropped.
        deepl_pick = r['deepl'].strip().lower()
        kept = [s for s in senses if not looks_suspicious(s, r['word'])]
        # Move deepl pick to the front if present
        kept_lower = [s.lower() for s in kept]
        if deepl_pick in kept_lower:
            idx = kept_lower.index(deepl_pick)
            kept = [kept[idx]] + kept[:idx] + kept[idx + 1:]
        elif kept:
            pass  # leave order
        else:
            kept = [r['deepl']]
        proposed = '/'.join(kept)
        if proposed.lower() == r['current'].lower():
            continue
        proposals.append({
            'rank': r['rank'],
            'article': r.get('article'),
            'word': r['word'],
            'current': r['current'],
            'proposed': proposed,
            'deepl': r['deepl'],
        })

    proposals.sort(key=lambda p: p['rank'] or 0)

    lines = [f'# Proposed sense-reorderings (drop suspicious lead senses)\n']
    lines.append(f'**{len(proposals)} entries**\n')
    lines.append('| rank | art | word | current | → proposed | DeepL pick |')
    lines.append('|---:|:---:|---|---|---|---|')
    for p in proposals:
        lines.append(f'| {p["rank"]} | {p["article"] or ""} | {p["word"]} | {p["current"]} | **{p["proposed"]}** | {p["deepl"]} |')
    OUT.write_text('\n'.join(lines), encoding='utf-8')

    (DIFF / 'proposed_reorderings.json').write_text(
        json.dumps(proposals, ensure_ascii=False, indent=2), encoding='utf-8'
    )

    print(f'Found {len(proposals)} entries with suspicious primary sense')
    for p in proposals[:20]:
        print(f'  r={p["rank"]:>5}  {p["article"] or "":>3} {p["word"]:<20}  {p["current"]!r:<55}  -> {p["proposed"]!r}')


if __name__ == '__main__':
    main()
