/* Generate a browser-script data URI for the Berlin Runner hero.
 *
 * Browsers do not allow GLTFLoader to fetch a neighbouring .glb when the
 * game is opened directly as a file:// page. A classic local <script> is
 * allowed, so this generated companion exposes the same bytes as a data URI.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const repo = path.resolve(__dirname, '..');
const version = process.argv[2] || 'v10';
if (!/^v\d+$/.test(version)) throw new Error(`Invalid hero version: ${version}`);
const stem = `berlin-runner-hero-${version}`;
const globalName = `BERLIN_RUNNER_HERO_${version.toUpperCase()}_DATA_URI`;
const input = path.join(repo, 'assets', 'models', `${stem}.glb`);
const output = path.join(repo, 'assets', 'models', `${stem}.inline.js`);
const bytes = fs.readFileSync(input);
const encoded = bytes.toString('base64');

const source =
  "'use strict';\n" +
  `// Generated by tools/embed_hero_data.cjs from ${stem}.glb.\n` +
  `globalThis.${globalName} = 'data:model/gltf-binary;base64,` +
  encoded + "';\n";

fs.writeFileSync(output, source);
console.log(`Wrote ${path.relative(repo, output)} (${bytes.length} GLB bytes)`);
