/* Generate a browser-script data URI for the Berlin Runner hero.
 *
 * Browsers do not allow GLTFLoader to fetch a neighbouring .glb when the
 * game is opened directly as a file:// page. A classic local <script> is
 * allowed, so this generated companion exposes the same bytes as a data URI.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const repo = path.resolve(__dirname, '..');
const input = path.join(repo, 'assets', 'models', 'berlin-runner-hero-v9.glb');
const output = path.join(repo, 'assets', 'models', 'berlin-runner-hero-v9.inline.js');
const bytes = fs.readFileSync(input);
const encoded = bytes.toString('base64');

const source =
  "'use strict';\n" +
  '// Generated by tools/embed_hero_data.cjs from berlin-runner-hero-v9.glb.\n' +
  "globalThis.BERLIN_RUNNER_HERO_V9_DATA_URI = 'data:model/gltf-binary;base64," +
  encoded + "';\n";

fs.writeFileSync(output, source);
console.log(`Wrote ${path.relative(repo, output)} (${bytes.length} GLB bytes)`);
