/* Bundle Berlin Runner's painted art into a data-URI companion for file://.
 *
 * A double-clicked file:// page cannot use these textures at all. three.js
 * requests them with `crossOrigin='anonymous'` (confirmed: r156's TextureLoader
 * defaults to it), and Chrome answers:
 *
 *     Access to image at 'file:///.../berlin-skyline-strip.png' from origin
 *     'null' has been blocked by CORS policy: Cross origin requests are only
 *     supported for protocol schemes: chrome, chrome-extension,
 *     chrome-untrusted, data, http, https, isolated-app.
 *
 * Both loaders swallow that failure silently, so the symptom is not an error:
 * the skyline band never switches on (leaving the procedural ring boxes and the
 * 3D Fernsehturm in its place) and the street-art atlas is simply absent. The
 * game looks fine, just wrong -- which is exactly why this went unnoticed.
 *
 * `data:` is on that allow-list, which is why the hero GLB already ships this
 * way. Unlike tools/inline_baltic_assets.py these bytes are passed through
 * verbatim rather than re-encoded: both files are cel-shaded art with hard ink
 * outlines, the strip needs its alpha, and JPEG ringing on those outlines is
 * the one artefact the horizon cannot hide.
 *
 *     node tools/inline_berlin_art.cjs
 */
'use strict';

const fs = require('fs');
const path = require('path');

const repo = path.resolve(__dirname, '..');
const img = path.join(repo, 'assets', 'img');
const output = path.join(img, 'berlin-art.inline.js');

// slot -> file, matching the ASSETS slot names in berlin-runner.html
const SLOTS = [
  ['summerSky', 'berlin-summer-sky-v1.png'],
  ['skylineStrip', 'berlin-skyline-strip.png'],
  ['streetArt', 'berlin-street-art-atlas-v1-1024.png']
];

const parts = [];
let total = 0;

for (const [slot, file] of SLOTS) {
  const bytes = fs.readFileSync(path.join(img, file));
  total += bytes.length;
  const encoded = bytes.toString('base64');
  console.log(
    `  ${slot.padEnd(13)} ${file.padEnd(38)} ${(bytes.length / 1024).toFixed(0).padStart(5)} KB` +
    ` -> ${(encoded.length / 1024).toFixed(0)} KB base64`
  );
  parts.push(`  ${slot}: 'data:image/png;base64,${encoded}'`);
}

const header =
  "'use strict';\n" +
  '// Generated by tools/inline_berlin_art.cjs - do not edit.\n' +
  "// Loaded only on file://, where Chrome's CORS policy blocks every local\n" +
  '// image but allows data: URIs. A served build ignores this file entirely and\n' +
  '// keeps the small, separately cacheable PNGs.\n' +
  'globalThis.BERLIN_RUNNER_ART = {\n';

fs.writeFileSync(output, header + parts.join(',\n') + '\n};\n');
console.log(`\n  -> ${path.relative(repo, output)}`);
console.log(
  `  raw ${(total / 1048576).toFixed(1)} MB, file ` +
  `${(fs.statSync(output).size / 1048576).toFixed(1)} MB`
);
